### ISSUE TITLE
Is it possible to add api for password encryption when logging in jasper server

### ISSUE THREAD

**Issue by TestOverload** [Jaspersoft/jrs-rest-java-client#1]
I found that jasper server support RSA password encryption when logging in. Is it possible  to add an autodetection and handle this case?

**Comment by Nazaf** [comment]
I am stuck at this as for now. What i am not getting is. Do i have to write a service for it or i have to just enable the service in JasperServer and hit that?

**Comment by yaroslav-kovalchyk** [comment]
>>>> This library automatically encrypts your password before send it if encryption is on, so to authenticate you need just specify login and password (not encrypted) in authenticate() method.

I found in documentation sentence above. Please tern password encryption on (on a server) and try to use client as usually (with not encrypted password). It should work for you. If not - please reopen this issue.
