### ISSUE TITLE
Add support for /rest_v2/bundles service

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#102]
Currently there is no support for resource bundles service. We had our own adapter to work around this, but it got broken in latest version of client (https://github.com/Jaspersoft/jrs-rest-java-client/issues/101)

When implementing this service, please keep in mind that it would work under anonymous user (https://github.com/Jaspersoft/jrs-rest-java-client/issues/63)

**Comment by yaroslav-kovalchyk** [comment]
Fixed https://github.com/TanyaEf/jrs-rest-java-client/commit/2cf0bad01fbfee0d5680f68c1fcdb7b9c6a938ea
