### ISSUE TITLE
Report service, prepareForRun method - it should be possible to run report without specifying number of the page

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#104]
Currently in order to run report synchronously, we need to call prepareForRun method, where you should specify pages or range parameter. In fact for the service itself page parameter is optional, it should be possible to run report execution without specifying this parameter (all pages will be requested).

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/TanyaEf/jrs-rest-java-client/commit/76982d998abdb759e4fa47f5f6cf50a211a6f8b2
