### ISSUE TITLE
ReportExecutionRequest setOutputFormat should have ReportOutputFormat enum as parameter

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#105]
There is inconsistency in running report synchronously and asynchronously. While prepareForRun method of ReportsAdapter accepts value of ReportOutputFormat enum, setOutputFormat method of ReportExecutionRequest accepts String. Should be enum in both cases

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/TanyaEf/jrs-rest-java-client/commit/76982d998abdb759e4fa47f5f6cf50a211a6f8b2
