### ISSUE TITLE
ResourceThumbnailListWrapper returns object from client, not from DTO

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#107]
`ResourceThumbnailListWrapper` contains a list of `com.jaspersoft.jasperserver.jaxrs.client.dto.thumbnails.ResourceThumbnail`, while it should return DTO objects of type  `com.jaspersoft.jasperserver.dto.thumbnails.ResourceThumbnail`

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/Jaspersoft/jrs-rest-java-client/commit/a0d69b571b25d7a11f19a6b16ab366cc17edb38a
