### ISSUE TITLE
There is no differentiation between GET and POST calls to thumbnails service (batch mode)

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#108]
REST v2 thumbnails service has two ways to get several thumbnails with one request: POST and GET. In the rest client only get is implemented, we need both options

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/Jaspersoft/jrs-rest-java-client/commit/a0d69b571b25d7a11f19a6b16ab366cc17edb38a
