### ISSUE TITLE
Provision of queryFilterString in Query

### ISSUE THREAD

**Issue by vaibhavguptaIITD** [Jaspersoft/jrs-rest-java-client#111]
Hi,

To use `queryExecutorService` we have to a pass `Query` object. The xml representation of `Query` object should be:

```xml
	<query>
  		<queryFields>
    		<queryField id="inv_store.inv_store__store_name" />
    		<queryField id="inv_store.inv_store__store_type" />
    		<queryField id="inv_store__store_contact.inv_store__store_contact__store_manager" />
  		</queryFields>
  		<queryFilterString>inv_store__region.inv_store__region__sales_state_province == 'CA'</queryFilterString>
	</query>
```
`Query` has `setQueryFields` method to provide `queryFields` but I am unable to find out the way to provide `queryFilterString`. Is there anyother way to use `queryExecutorService`? Please suggest.

**Comment by yaroslav-kovalchyk** [comment]
Fixed in master branch. Will be available in new release.
