### ISSUE TITLE
Calls to thumbnails service with non-existing/invalid URIs should return response with status code, but not throw exception

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#112]
If run the following code
```java
OperationResult<InputStream> result = session
       .thumbnailsService()
       .thumbnail()
       .report("/some")
       .get();
```
`ResourceNotFoundException` will be thrown. With the following
```java
OperationResult<InputStream> result = session
       .thumbnailsService()
       .thumbnail()
       .report("/")
       .get();
```
`RequestedRepresentationNotAvailableForResourceException: Not Acceptable` will be thrown. Client should return response with status code from JRS, instead of throwing exception. Also there is `NPE` if I run the following
```java
OperationResult<InputStream> result = session
      .thumbnailsService()
      .thumbnail()
      .get();
```

**Comment by tmatveyeva** [comment]
After discussion with Yaroslav, we agreed, that there should be two strategies in client for such cases (configured):
- throw exception and provide response in exception
- return null entity and response with status from JRS

**Comment by yaroslav-kovalchyk** [comment]
Would be great to have ability to get ErrorDescriptor if available

**Comment by yaroslav-kovalchyk** [comment]
Now it's possible with new error handling strategy
