### ISSUE TITLE
Profile attributes services should return object from JRS DTO, not from client

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#114]
Currently server attribute service returns ServerAttribute class and tenant attribute - ClientTenantAttribute, both implemented within client. There is a public DTO object in JRS jar, called ClientUserAttribute, that is used for all cases (it will remain as is, but new one will be created in nearest future: ClientAttribute). So, all three services should use same DTO class from JRS

**Comment by yaroslav-kovalchyk** [comment]
Fixed
