### ISSUE TITLE
Get tenant attributes throws NPE

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#117]
```java
OperationResult<TenantAttributesListWrapper> result3 = getRestClient(superuser)
        .organizationsService()
        .organization("organization_1")
        .attributes()
        .get();
```
The following code will throw `NPE`.

**Comment by TanyaEf** [comment]
I tested the code on 6.0.7 version of JasperserverRestClient, it works fine.

**Comment by TanyaEf** [comment]
I'm sorry,  there is a hudge byg in the service, we need fix it immidetly

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/Jaspersoft/jrs-rest-java-client/commit/a0d69b571b25d7a11f19a6b16ab366cc17edb38a
