### ISSUE TITLE
Bundles service, forLocale should accept Locale, not only string

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#123]
Currently there is only one method to bundle for locale: 
    public BundlesService forLocale(String locale)

It would be more convenient to be able to pass Locale object directly

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/Jaspersoft/jrs-rest-java-client/commit/a0d69b571b25d7a11f19a6b16ab366cc17edb38a
