### ISSUE TITLE
Bundles service doesn't work

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#124]
pom.xml for sample:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jaspersoft.qa</groupId>
    <artifactId>rest-client-sample</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.jaspersoft.jasperserver</groupId>
            <artifactId>jasperserver-dto</artifactId>
            <version>6.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.jaspersoft</groupId>
            <artifactId>jrs-rest-java-client</artifactId>
            <version>6.0.7</version>
        </dependency>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.9.4</version>
        </dependency>
    </dependencies>

</project>

test class:

public class SampleTest {

    @Test
    public void test_getBundles(){
        RestClientConfiguration configuration = new RestClientConfiguration("http://localhost:8080/jasperserver-pro");
        JasperserverRestClient restClient = new JasperserverRestClient(configuration);

        JSONObject bundles = restClient.authenticate("jasperadmin", "jasperadmin")
                .bundlesService()
                .forLocale("en_US")
                .allBundles()
                .getEntity();
        Assert.assertTrue(bundles.has("jasperserver_messages"));
    }
}

Entity is null and bundles contains empty collection

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/Jaspersoft/jrs-rest-java-client/commit/a0d69b571b25d7a11f19a6b16ab366cc17edb38a
