### ISSUE TITLE
Resource descriptor entity is null in rest client 6.0.8

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#126]
When run the following code:

 client.authenticate(superuser, superuser).resourcesService()
                .resource("/organizations/organization_1/Domains/supermartDomain").details().getEntity();

Details contains status 200, but entity is null. This is blocker for update to 6.0.8 version

**Comment by yaroslav-kovalchyk** [comment]
Fixed
