### ISSUE TITLE
Error using the 6.0.8 maybe java version

### ISSUE THREAD

**Issue by thomatech** [Jaspersoft/jrs-rest-java-client#128]
We're just embarking on upgrading our existing (tomcat6/java 1.6) system using this client. We did a test against 6.0.1 and that seemed to work ok.

However, now were getting started in earnest we tried 6.0.8 and are getting the following error. 

UnsupportedClassVersionError: org/glassfish/jersey/jackson/JacksonFeature : Unsupported major.minor version 51.0 (unable to load class org.glassfish.jersey.jackson.JacksonFeature)

Googling around it seems likely that it's due to the java version the jars are compiled with being greater that our existing app.

It is possible to recompile 6.0.8 with dependencies against java version 1.6? If not are there instructions on how to build 6.0.8 with dependencies so we can attempt this ourselves.

**Comment by yaroslav-kovalchyk** [comment]
This is a regular Maven project. You can easily build it by yourself using Maven. Please follow steps from here:
https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

But please skip step Creating a Project and do checkout of this rest-client instead.
