### ISSUE TITLE
bundles service - can we specify uri to search under for the bundle?

### ISSUE THREAD

**Issue by thomatech** [Jaspersoft/jrs-rest-java-client#132]
It looks to me like the bundleService is expecting all the bundles to be under a /bundles uri.  Is this the case? Surely there should be an interface so we can specify where the bundle files exist?

We co-located all our bundle files under the report URI as this help facilite deployment of individual reports and all their collateral around to our localized installations.

**Comment by yaroslav-kovalchyk** [comment]
This service provides access to bundles, saved in WEB-INF/bundles directory of JasperReports Server deployment. You can find declaration of message source for this service in server side configuration file applicationContext-rest-services.xml, bean ID "exposedMessageSource". If you want to access your bundles, saved in a repository, then you have to use repository service and access your bundles by their URIs.
