### ISSUE TITLE
StringIndexOutOfBoundsException if try to get "/" URI

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#137]
Try to run the following test:

    @Test
    public void test_resourceService() {
        RestClientConfiguration configuration = new RestClientConfiguration("http://localhost:8080/jasperserver-pro");
        JasperserverRestClient client = new JasperserverRestClient(configuration);
        Session session = client.authenticate("superuser", "superuser");
        OperationResult<ClientResource> result = session.resourcesService()
                .resource("/").get(ClientResource.class);
        Assert.assertTrue(result.getResponse().getStatus() == 200);
    }

As a result I get: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at com.jaspersoft.jasperserver.jaxrs.client.apiadapters.resources.ResourcesTypeResolverUtil.getClassForMime(ResourcesTypeResolverUtil.java:103)
	at com.jaspersoft.jasperserver.jaxrs.client.core.operationresult.OperationResultFactoryImpl.getSpecificResourceType(OperationResultFactoryImpl.java:74)

Please note that 

        OperationResult<ClientResource> result = session.resourcesService()
                .resource("/").details();
and 

        OperationResult<ClientFolder> result = session.resourcesService()
                .resource("/").get(ClientFolder.class);

work fine

**Comment by yaroslav-kovalchyk** [comment]
fixed
