### ISSUE TITLE
Attributes service creates attributes, but do not associate permissions with it

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#139]
If we have profile attribute defined as follows: 

    <bean id="pattrTenantAttribute" class="com.jaspersoft.jasperserver.dto.authority.ClientUserAttribute">
        <property name="name" value="OrganizationAttributeTest"/>
        <property name="value" value="Organization attribute test value"/>
        <property name="description" value="Organization attribute description"/>
        <property name="permissionMask" value="32"/>
        <property name="secure" value="false"/>
        <property name="inherited" value="false"/>
        <property name="holder" value="tenant:/organization_1"/>
    </bean>

(Permission mask is different than administrate)

and run the following request:

                    session.attributesService()
                            .forOrganization("organization_1)
                            .attribute("OrganizationAttributeTest")
                            .setIncludePermissions(true)
                            .createOrUpdate(attribute);

Attribute is created, but permission mask would be 1 (administrate)

**Comment by yaroslav-kovalchyk** [comment]
Fixed

**Comment by tmatveyeva** [comment]
Issue is not fixed in 6.1.1
Test code:

Maven dependency:
        <dependency>
            <groupId>com.jaspersoft</groupId>
            <artifactId>jrs-rest-java-client</artifactId>
            <version>6.1.1</version>
        </dependency>

Attribute:

    <bean id="executeOnlyAttribute" class="com.jaspersoft.jasperserver.dto.authority.hypermedia.HypermediaAttribute">
        <property name="name" value="ExecuteOnlyAttribute"/>
        <property name="value" value="Execute Only Attribute value"/>
        <property name="description" value="Execute Only Attribute description"/>
        <property name="permissionMask" value="32"/>
        <property name="secure" value="false"/>
        <property name="inherited" value="true"/>
        <property name="holder" value="tenant:/"/>
        <property name="embedded" ref="executeOnlyPermissionContainer"/>
    </bean>

    <bean id="executeOnlyPermission" class="com.jaspersoft.jasperserver.dto.permissions.RepositoryPermission">
        <property name="mask" value="0"/>
        <property name="recipient" value="role:/ROLE_ADMINISTRATOR"/>
    </bean>

    <bean id="executeOnlyPermissionContainer"  class="com.jaspersoft.jasperserver.dto.authority.hypermedia.HypermediaAttributeEmbeddedContainer">
        <property name="repositoryPermissions">
            <list value-type="com.jaspersoft.jasperserver.dto.permissions.RepositoryPermission">
                <ref bean="executeOnlyPermission"/>
            </list>
        </property>
    </bean>


Java code:

                    session.attributesService()
                            .attribute(executeOnlyAttribute.getName())
                            .setIncludePermissions(true)
                            .createOrUpdate(executeOnlyAttribute);

This will still create Administrate permission

I think to be able to make it work in client you need to pass HypermediaAttribute, not ClientUserAttribute

**Comment by yaroslav-kovalchyk** [comment]
Fixed
