### ISSUE TITLE
Client doesn't work with JBoss 8, because it sends 'path' cookie

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#150]
Currently REST client doesn't work on JBoss 8, because it sends path cookie to server:

05 Nov 2015 13:53:27  INFO SessionStorage - 1 * Sending client request on
thread main
1 > POST
http://infra-platforms-phase2-dev-445-qaa.pfa.jaspersoft.com:8080/jasperserver-pro/j_spring_security_check
1 > Content-Type: application/x-www-form-urlencoded
j_username=superuser&j_password=superuser

05 Nov 2015 13:53:27  INFO SessionStorage - 2 * Client response received on
thread main
2 < 302
2 < Connection: keep-alive
2 < Content-Length: 0
2 < Date: Thu, 05 Nov 2015 11:53:18 GMT
2 < Location:
http://infra-platforms-phase2-dev-445-qaa.pfa.jaspersoft.com:8080/jasperserver-pro/loginsuccess.html
2 < P3P: CP="ALL"
2 < Server: WildFly/8
2 < Set-Cookie:
JSESSIONID=yXhSA_N0ifeXO1xVNxTwvAlr.infra-platforms-phase2-dev-445-qaa;
path=/jasperserver-pro,userLocale=en_US;Expires=Fri, 6-Nov-2015 11:53:18
GMT;HttpOnly
2 < X-Powered-By: Undertow/1

Next request that would use cookie from this response will fail with Internal
Server Error

Error in jboss server log: 

2015-10-20 01:14:49,725 ERROR [io.undertow.request] (default task-46) UT005023:
Exception handling request to /jasperserver-pro/res
t_v2/import: java.lang.IllegalArgumentException: Cookie name "path" is a
reserved token

**Comment by tmatveyeva** [comment]
Loggin of http requests/responses for test

1 > GET http://infra-platforms-phase2-dev-453-qaa.pfa.jaspersoft.com:8080/jasperserver-pro/rest_v2/bundles?expanded=true
1 > Accept: application/json
1 > Accept-Language: 

06 Nov 2015 18:38:20  INFO SessionStorage - 1 * Client response received on thread main
1 < 500
1 < Connection: keep-alive
1 < Content-Length: 86
1 < Content-Type: text/html
1 < Date: Fri, 06 Nov 2015 16:38:10 GMT
1 < Set-Cookie: JSESSIONID=96JOW2J3uGGlJkiT6BH7OWg9.infra-platforms-phase2-dev-453-qaa; path=/jasperserver-pro
<html><head><title>Error</title></head><body>500 - Internal Server Error</body></html>

06 Nov 2015 18:38:20  INFO SessionStorage - 1 * Sending client request on thread main
1 > POST http://infra-platforms-phase2-dev-453-qaa.pfa.jaspersoft.com:8080/jasperserver-pro/j_spring_security_check
1 > Content-Type: application/x-www-form-urlencoded
j_username=superuser&j_password=superuser

06 Nov 2015 18:38:21  INFO SessionStorage - 1 * Client response received on thread main
1 < 302
1 < Connection: keep-alive
1 < Content-Length: 0
1 < Date: Fri, 06 Nov 2015 16:38:10 GMT
1 < Location: http://infra-platforms-phase2-dev-453-qaa.pfa.jaspersoft.com:8080/jasperserver-pro/loginsuccess.html
1 < P3P: CP="ALL"
1 < Server: WildFly/8
1 < Set-Cookie: JSESSIONID=OTixpUCcr7QFqeHTwJP9YIO9.infra-platforms-phase2-dev-453-qaa; path=/jasperserver-pro,userLocale=en_US;Expires=Sat, 7-Nov-2015 16:38:11 GMT;HttpOnly
1 < X-Powered-By: Undertow/1

**Comment by TanyaEf** [comment]
We tried to reproduce the bug but on our environment the client works fine. Here are our logs:
```

2015-11-16 15:03:38,771 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 1 * Sending client request on thread main
1 > POST http://localhost:8180/jasperserver/j_spring_security_check
1 > Content-Type: application/x-www-form-urlencoded
j_username=superuser&j_password=superuser

2015-11-16 15:03:38,846 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 1 * Client response received on thread main
1 < 302
1 < Connection: keep-alive
1 < Content-Length: 0
1 < Date: Mon, 16 Nov 2015 13:03:38 GMT
1 < Location: http://localhost:8180/jasperserver/loginsuccess.html
1 < P3P: CP="ALL"
1 < Server: Wildfly 8
1 < Set-Cookie: JSESSIONID=MphNsBnejVZ4x_35RvX1yr3w.hrk1-lhp-f49400; path=/jasperserver,userLocale=en_US;Expires=Tue, 17-Nov-2015 13:03:38 GMT;HttpOnly
1 < X-Powered-By: Undertow 1

2015-11-16 15:03:38,864 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 2 * Sending client request on thread main
2 > PUT http://localhost:8180/jasperserver/rest_v2/users/test_user
2 > Accept: application/json
2 > Content-Type: application/json
{"fullName":"John Doe","password":"test_password","emailAddress":"john.doe@email.net","externallyDefined":false,"enabled":true,"username":"test_user"}

2015-11-16 15:03:38,886 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 2 * Client response received on thread main
2 < 201
2 < Connection: keep-alive
2 < Content-Type: application/json
2 < Date: Mon, 16 Nov 2015 13:03:38 GMT
2 < P3P: CP="ALL"
2 < Server: Wildfly 8
2 < Transfer-Encoding: chunked
2 < X-Powered-By: Undertow 1
{"fullName":"John Doe","emailAddress":"john.doe@email.net","externallyDefined":false,"enabled":true,"username":"test_user","roles":[{"name":"ROLE_USER","externallyDefined":false}]}
```

And for BunleSrevice:
```

2015-11-16 15:07:28,284 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 6 * Sending client request on thread main
6 > GET http://localhost:8180/jasperserver/rest_v2/bundles?expanded=true
6 > Accept: application/json
6 > Accept-Language: en-US

2015-11-16 15:07:28,290 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 6 * Client response received on thread main
6 < 200
6 < Cache-Control: no-transform, max-age=86400
6 < Connection: keep-alive
6 < Content-Type: application/json
6 < Date: Mon, 16 Nov 2015 13:07:28 GMT
6 < P3P: CP="ALL"
6 < Server: Wildfly 8
6 < Set-Cookie: JSESSIONID=Gf54n6vBnTSEHkI15oEiPasY.hrk1-lhp-f49400; path=/jasperserver,userLocale=en_US;Expires=Tue, 17-Nov-2015 13:07:28 GMT;HttpOnly
6 < Transfer-Encoding: chunked
6 < Vary: Accept-Language
6 < X-Powered-By: Undertow 1
{"jasperserver_messages":{"jsp.JSErrorPage.errorTrace":"Error Trace","logCollectors.form.resourceUri.hint":"Resource must be a report or Ad Hoc view.","resource.file.edit":"Edit File","error.not.empty.trigger.months":"Specify the months when the job should run.","OlapUnitValidator.error.invalid.schema.source":"Select a valid schema source.","CRUDUserValidator.error.not.empty.user.password":"Enter a password.","xmla.title":"Accessing Mondrian by XML\/A","resource.datasource.custom.page.title.add":"Add Data Source","jasper.report.view.page.label":"Page","MondrianXmlaSourceValidator.error.invalid.chars.mondrianXmlaDefinition.catalog":"The Catalog field contains invalid characters. You might have mistyped it.","jsp.olap.empty.message":...and more..
```

**Comment by yaroslav-kovalchyk** [comment]
please try to run client's integration tests. How to run is described here: https://github.com/Jaspersoft/jrs-rest-java-client-tests#running-application
Please reopen if you will be able to reproduce this issue via this integration tests.
