### ISSUE TITLE
CVS exporting 

### ISSUE THREAD

**Issue by dasung** [Jaspersoft/jrs-rest-java-client#162]
Hi,

I want to know whether rest-client works for CVS export. 
It is not working just setOutputFormat("csv").

Thank you.

**Comment by TanyaEf** [comment]
The client works with CSV format fine, whether you specify output format as enum (`.setOutputFormat(ReportOutputFormat.CSV)`) or as String (`.setOutputFormat("csv")`), in 
synchronous and asynchronous modes.
Here is the code of test:
[https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L57](https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L57)

[https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L188](https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L188)

[https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L309](https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L309)

[https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L349](https://github.com/Jaspersoft/jrs-rest-java-client-tests/blob/master/src/test/java/com/jaspersoft/jasperserver/jaxrs/client/apiadapters/reporting/ReportingServiceTest.java#L349)

Here you can download our test suite and try it on your environment:

[https://github.com/Jaspersoft/jrs-rest-java-client-tests](https://github.com/Jaspersoft/jrs-rest-java-client-tests)
If bug happens again, please provide more information and reopen the issue.

**Comment by dasung** [comment]
Hi Tanya,

It is working. Thanks!!
