### ISSUE TITLE
Passing user time zone to report generation

### ISSUE THREAD

**Issue by Tanrikut** [Jaspersoft/jrs-rest-java-client#166]
Is there a way to set REPORT_TIME_ZONE in report execution?

**Comment by yaroslav-kovalchyk** [comment]
It's a very good question. REST service itself supports setting timezone in following ways:
1) User is able to specify timezone within login request (/j_spring_security_check). Scope for this timezone value is session (if not overridden in particular request). 
2) User can send 'Accept-Timezone' HTTP header within any request (e.g. while starting report execution). Scope for this timezone is request.
Unfortunately both ways are not accessible via this client API. I find it`s a good enhancement. We will proceed with solution.

**Comment by TanyaEf** [comment]
Ability ti set time zone is available in master branch and will be available in nearest release.
