### ISSUE TITLE
Add an ability to search for attributes

### ISSUE THREAD

**Issue by leonidbondar** [Jaspersoft/jrs-rest-java-client#167]
We need the ability to search attributes not only by name but also by group, holder, recursive, offset and limit parameters and its combinations (Supported by service)

Requests could be formed as:
Method  GET
URL     {JRS_URL}/rest_v2/attributes?_embedded=permission&name={attributeName1}&group={groupName}&holder={holderId}&includeInherited={true|false}&recursive={true|false}&offset={offset}&limit={limit}

**Comment by yaroslav-kovalchyk** [comment]
Good point. We have to extend attribute search API.

**Comment by TanyaEf** [comment]
Ability to use search parameters is available in master and will be included in nearest release
