### ISSUE TITLE
Job Scheduling and Paramters

### ISSUE THREAD

**Issue by kc5mzr** [Jaspersoft/jrs-rest-java-client#17]
I have a Report with 1 Parameter that takes a string value.   It looks like the value is not getting to the server.   It shows as ~NULL~ in the Job that's returned from scheduling and the report that's returned is empty like there was no parameter value.

```
Map<String, Object> reportParameters = new HashMap<String, Object>();
reportParameters.put("po",(Object) new ArrayList<String(Arrays.asList("WAKE")));
JobSource jobSource = new JobSource();
jobSource.setReportUnitURI("/Production_Reports/MonthlyCleanup/monthly_cleanup");
jobSource.setParameters(reportParameters);
```

I can see the parameters in the JobSource before the schedule.

```
System.out.println("Built JobSource=" + jobSource);
 Built JobSource=JobSource=JobSource{reportUnitURI='/Production_Reports/MonthlyCleanup/monthly_cleanup', parameters={po=[WAKE]}}
```

But the value comes back as NULL after scheduling.

```
OperationResult<Job> result = session.jobsService().scheduleReport(job);
Job sJob = result.getEntity();
System.out.println("\nScheduled JobSource=" + sJob.getSource());
Scheduled JobSource=JobSource{reportUnitURI='/Production_Reports/MonthlyCleanup/monthly_cleanup', parameters={po=[~NULL~]}}
```

I'm using the latest snapshot jar from the 16th, with Jasper 5.5.0.  The job executes without any errors.  It just doesn't return any output.

**Comment by kodiraj** [comment]
the issue is happening again in the latest release. 

i am passing the parameters but the output doesn't have any,
