### ISSUE TITLE
How to create a report unit with datasource references

### ISSUE THREAD

**Issue by RamyaSridhara** [Jaspersoft/jrs-rest-java-client#171]
I am trying to create a reportunit 
  OperationResult<ClientResource> createNewRUResponse = jasperSession
	            .resourcesService()
	            .resource(reportsPath)
	            .createNew(unit); 

ClientReportUnit does not take in datasource reference.Meaning refer to already created datasource in the server instead of creating a new one.
is that possible with this client library?

**Comment by yaroslav-kovalchyk** [comment]
Yes, it's possible. Please use ClientReference in a following way:
unit.setDataSource(new ClientReference("/your/data/source/uri"));
Please reopen if it doesn't work.
