### ISSUE TITLE
Add ability to send PATCH requests directily

### ISSUE THREAD

**Issue by TanyaEf** [Jaspersoft/jrs-rest-java-client#182]
The current version of JRS 6.2 supports PATCH requests, but the client doesn't allow to sent requests with this method. Now in the client we use "X-HTTP-Method-Override"  header and POST requests. 

The issue is to find a way to update environment or config the client to send PATCH requests directly.

**Comment by yaroslav-kovalchyk** [comment]
For now it's OK to send PATCH via POST. It's even better, because some secure environment do not allow to send anything but GET and POST. So, let's keep this way of sending PATCH via POST for now.
