### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by RaviTeja457** [Jaspersoft/jrs-rest-java-client#188]
02-22 02:04:21.395 12810-12810/org.readium.sdk.android D/WebViewActivity: onPageStarted: file:///android_asset/readium-shared-js/reader.html
02-22 02:04:30.456 12810-12839/org.readium.sdk.android W/EGL_emulation: eglSurfaceAttrib not implemented
02-22 02:04:30.456 12810-12839/org.readium.sdk.android W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf114d80, error=EGL_SUCCESS
02-22 02:04:30.489 12810-12810/org.readium.sdk.android W/art: Attempt to remove local handle scope entry from IRT, ignoring
02-22 02:04:30.490 12810-12810/org.readium.sdk.android W/AwContents: onDetachedFromWindow called when already detached. Ignoring
02-22 02:04:30.493 12810-12810/org.readium.sdk.android W/art: Attempt to remove local handle scope entry from IRT, ignoring
02-22 02:04:30.493 12810-12810/org.readium.sdk.android W/art: Attempt to remove local handle scope entry from IRT, ignoring
02-22 02:04:30.598 12810-12839/org.readium.sdk.android W/EGL_emulation: eglSurfaceAttrib not implemented
02-22 02:04:30.598 12810-12839/org.readium.sdk.android W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdf3f4380, error=EGL_SUCCESS
02-22 02:04:30.753 12810-12810/org.readium.sdk.android D/WebViewActivity: onPageStarted: file:///android_asset/readium-shared-js/reader.html
02-22 02:04:30.880 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(11838)] "RequireJS ... cfi_errors", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (11838)
02-22 02:04:30.880 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(12225)] "RequireJS ... cfi_instructions", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (12225)
02-22 02:04:30.881 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(12662)] "RequireJS ... cfi_interpreter", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (12662)
02-22 02:04:30.881 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(13168)] "RequireJS ... cfi_generator", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (13168)
02-22 02:04:30.881 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(13315)] "RequireJS ... cfi_API", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (13315)
02-22 02:04:30.881 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(32)] "DOM READY", source: file:///android_asset/readium-shared-js/host_app_feedback.js (32)
02-22 02:04:30.881 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(0)] "'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).", source:  (0)
02-22 02:04:30.881 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(0)] "Discontiguous selection is not supported.", source: file:///android_asset/readium-shared-js/reader.html (0)
02-22 02:04:30.899 12810-12810/org.readium.sdk.android D/WebViewActivity: onPageFinished: file:///android_asset/readium-shared-js/reader.html
02-22 02:04:30.905 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(13302)] "#######################################", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (13302)
02-22 02:04:30.917 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(18716)] "Globals...", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (18716)
02-22 02:04:30.917 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(18719)] "ReadiumSDK extend.", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (18719)
02-22 02:04:30.923 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(35)] "globalsSetup READY", source: file:///android_asset/readium-shared-js/host_app_feedback.js (35)
02-22 02:04:30.923 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(18773)] "Plugins included: ", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (18773)
02-22 02:04:30.972 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(38)] "reader_view READY", source: file:///android_asset/readium-shared-js/host_app_feedback.js (38)
02-22 02:04:30.987 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(42171)] "** EL is a string:viewport", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (42171)
02-22 02:04:30.987 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(233)] "DONE READER", source: file:///android_asset/readium-shared-js/host_app_feedback.js (233)
02-22 02:04:31.010 12810-13259/org.readium.sdk.android D/WebViewActivity: onReaderInitialized
02-22 02:04:31.010 12810-13259/org.readium.sdk.android D/WebViewActivity: openPageRequestData: org.readium.sdk.android.launcher.model.OpenPageRequest@2e97100
02-22 02:04:31.018 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(18754)] "Plugins loaded.", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (18754)
02-22 02:04:31.018 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(211)] "undefined", source: file:///android_asset/readium-shared-js/host_app_feedback.js (211)
02-22 02:04:31.018 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(225)] "undefined", source: file:///android_asset/readium-shared-js/host_app_feedback.js (225)
02-22 02:04:31.043 12810-13259/org.readium.sdk.android D/WebViewActivity: onSettingsApplied
02-22 02:04:31.145 12810-13233/org.readium.sdk.android D/WebViewActivity: -------- shouldInterceptRequest: http://127.0.0.1:8080/chapter_131.xhtml
02-22 02:04:31.145 12810-13233/org.readium.sdk.android D/WebViewActivity: http://127.0.0.1:8080/chapter_131.xhtml => chapter_131.xhtml
02-22 02:04:31.146 12810-13233/org.readium.sdk.android D/WebViewActivity: RESOURCE FETCH ... http://127.0.0.1:8080/chapter_131.xhtml
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer: GET '/chapter_131.xhtml' 
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'host' = '127.0.0.1:8080'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'connection' = 'keep-alive'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept' = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'user-agent' = 'Mozilla/5.0 (Linux; Android 5.1; Google Nexus 4 - 5.1.0 - API 22 - 768x1280 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept-encoding' = 'gzip, deflate'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept-language' = 'en-IN,en-US;q=0.8'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'x-requested-with' = 'org.readium.sdk.android'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:764]: Package.nativeInputStreamForRelativePath(): received relative path 'chapter_131.xhtml'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:766]: Package.nativeInputStreamForRelativePath(): package base path 'OPS/'
02-22 02:04:31.153 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:768]: Package.nativeInputStreamForRelativePath(): final path 'OPS/chapter_131.xhtml'
02-22 02:04:31.156 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:116]: JNI --- GetAllBytes ...
02-22 02:04:31.156 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:145]: JNI --- GetAllBytes: 3002
02-22 02:04:31.156 12810-13561/org.readium.sdk.android D/WebViewActivity: PRE-PROCESSED HTML: chapter_131.xhtml
02-22 02:04:31.163 12810-13233/org.readium.sdk.android D/WebViewActivity: -------- shouldInterceptRequest: http://127.0.0.1:8080/1/readium_epubReadingSystem_inject.js
02-22 02:04:31.163 12810-13233/org.readium.sdk.android D/WebViewActivity: http://127.0.0.1:8080/1/readium_epubReadingSystem_inject.js => 1/readium_epubReadingSystem_inject.js
02-22 02:04:31.164 12810-13233/org.readium.sdk.android D/WebViewActivity: navigator.epubReadingSystem inject ...
02-22 02:04:31.169 12810-13233/org.readium.sdk.android D/WebViewActivity: -------- shouldInterceptRequest: http://127.0.0.1:8080/css/stylesheet.css
02-22 02:04:31.169 12810-13233/org.readium.sdk.android D/WebViewActivity: http://127.0.0.1:8080/css/stylesheet.css => css/stylesheet.css
02-22 02:04:31.170 12810-13233/org.readium.sdk.android D/WebViewActivity: RESOURCE FETCH ... http://127.0.0.1:8080/css/stylesheet.css
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer: GET '/css/stylesheet.css' 
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'host' = '127.0.0.1:8080'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'connection' = 'keep-alive'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept' = 'text/css,*/*;q=0.1'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'user-agent' = 'Mozilla/5.0 (Linux; Android 5.1; Google Nexus 4 - 5.1.0 - API 22 - 768x1280 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'referer' = 'http://127.0.0.1:8080/chapter_131.xhtml'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept-encoding' = 'gzip, deflate'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept-language' = 'en-IN,en-US;q=0.8'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'x-requested-with' = 'org.readium.sdk.android'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/EpubServer: NEW STREAM:/css/stylesheet.css
02-22 02:04:31.172 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:764]: Package.nativeInputStreamForRelativePath(): received relative path 'css/stylesheet.css'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:766]: Package.nativeInputStreamForRelativePath(): package base path 'OPS/'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:768]: Package.nativeInputStreamForRelativePath(): final path 'OPS/css/stylesheet.css'
02-22 02:04:31.172 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 8192 - 4485
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.172 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 4485
02-22 02:04:31.296 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:31.505 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:31.518 12810-13233/org.readium.sdk.android D/WebViewActivity: -------- shouldInterceptRequest: http://127.0.0.1:8080/fonts/STIXGeneral.otf
02-22 02:04:31.518 12810-13233/org.readium.sdk.android D/WebViewActivity: http://127.0.0.1:8080/fonts/STIXGeneral.otf => fonts/STIXGeneral.otf
02-22 02:04:31.518 12810-13233/org.readium.sdk.android D/WebViewActivity: RESOURCE FETCH ... http://127.0.0.1:8080/fonts/STIXGeneral.otf
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer: GET '/fonts/STIXGeneral.otf' 
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'host' = '127.0.0.1:8080'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'connection' = 'keep-alive'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'user-agent' = 'Mozilla/5.0 (Linux; Android 5.1; Google Nexus 4 - 5.1.0 - API 22 - 768x1280 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept' = '*/*'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'referer' = 'http://127.0.0.1:8080/css/stylesheet.css'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept-encoding' = 'gzip, deflate'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'accept-language' = 'en-IN,en-US;q=0.8'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer:   HDR: 'x-requested-with' = 'org.readium.sdk.android'
02-22 02:04:31.519 12810-13561/org.readium.sdk.android D/EpubServer: NEW STREAM:/fonts/STIXGeneral.otf
02-22 02:04:31.520 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:764]: Package.nativeInputStreamForRelativePath(): received relative path 'fonts/STIXGeneral.otf'
02-22 02:04:31.520 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:766]: Package.nativeInputStreamForRelativePath(): package base path 'OPS/'
02-22 02:04:31.520 12810-13561/org.readium.sdk.android I/libepub3 [./../../src/main/jni/packagejni.cpp:768]: Package.nativeInputStreamForRelativePath(): final path 'OPS/fonts/STIXGeneral.otf'
02-22 02:04:31.523 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(22834)] "EPUB doc iframe src:", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (22834)
02-22 02:04:31.523 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(22835)] "http://127.0.0.1:8080/chapter_131.xhtml", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (22835)
02-22 02:04:31.523 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(22836)] "EPUB doc iframe base URI:", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (22836)
02-22 02:04:31.523 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(22837)] "file:///android_asset/readium-shared-js/reader.html", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (22837)
02-22 02:04:31.523 12810-12810/org.readium.sdk.android D/WebViewActivity: onLoadResource: http://127.0.0.1:8080/chapter_131.xhtml
02-22 02:04:31.523 12810-12810/org.readium.sdk.android D/WebViewActivity: WebView evaluateJavascript: var epubRSInject =
                                                                          function(win) {
                                                                          var ret = '';
                                                                          ret += win.location.href;
                                                                          ret += ' ---- ';
                                                                          if (win.frames)
                                                                          {
                                                                          for (var i = 0; i < win.frames.length; i++)
                                                                          {
                                                                          var iframe = win.frames[i];
                                                                          ret += ' IFRAME ';
                                                                          if (iframe.readium_set_epubReadingSystem)
                                                                          {
                                                                          ret += ' EPBRS ';
                                                                          iframe.readium_set_epubReadingSystem(window.navigator.epubReadingSystem);
                                                                          }
                                                                          ret += epubRSInject(iframe);
                                                                          }
                                                                          }
                                                                          return ret;
                                                                          };
                                                                          epubRSInject(window);
02-22 02:04:31.523 12810-12810/org.readium.sdk.android D/WebViewActivity: WebView evaluateJavascript KitKat+ API
02-22 02:04:31.523 12810-12810/org.readium.sdk.android D/WebViewActivity: onLoadResource: http://127.0.0.1:8080/css/stylesheet.css
02-22 02:04:31.524 12810-12810/org.readium.sdk.android I/chromium: [INFO:CONSOLE(40791)] "Uncaught TypeError: undefined is not a function", source: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js (40791)
02-22 02:04:31.525 12810-12810/org.readium.sdk.android D/WebViewActivity: onLoadResource: http://127.0.0.1:8080/fonts/STIXGeneral.otf
02-22 02:04:31.530 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 8192 - 8192
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 8192
02-22 02:04:31.530 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 16384 - 16384
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 16384
02-22 02:04:31.530 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 32768 - 32768
02-22 02:04:31.530 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 32768
02-22 02:04:31.531 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 65536 - 65536
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 65536
02-22 02:04:31.531 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 131072 - 131072
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.531 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 131072
02-22 02:04:31.532 12810-13561/org.readium.sdk.android W/System.err: !!! ResourceInputStream int readX(int length, byte[] barray) 
02-22 02:04:31.532 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:162]: JNI --- GetBytes_ 1: 262144 - 160370
02-22 02:04:31.532 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:180]: JNI --- GetBytes_ FilterChainByteStream
02-22 02:04:31.532 12810-13561/org.readium.sdk.android D/libepub3 [./../../src/main/jni/resource_stream.cpp:194]: JNI --- GetBytes_ 2: 160370
02-22 02:04:31.631 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:31.777 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:31.957 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:31.967 12810-12810/org.readium.sdk.android D/WebViewActivity: WebView evaluateJavascript RETURN: "file:///android_asset/readium-shared-js/reader.html ----  IFRAME  EPBRS http://127.0.0.1:8080/chapter_131.xhtml ---- "
02-22 02:04:32.086 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.165 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.213 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.302 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.339 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.423 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.544 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.604 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.729 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.866 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:32.906 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:33.032 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:33.164 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)
02-22 02:04:33.242 12810-12839/org.readium.sdk.android E/eglCodecCommon: **** ERROR unknown type 0xc4e2e420 (glSizeof,80)

**Comment by yaroslav-kovalchyk** [comment]
Hello colleague,
I'm sorry, but didn't get what is the issue... Could you please describe what happens?
