### ISSUE TITLE
Issue with reading error messages on  wildfly 8.2.1 + MySQL 5.7

### ISSUE THREAD

**Issue by leonidbondar** [Jaspersoft/jrs-rest-java-client#189]
On wildfly 8.2.1 + MySQL 5.7 JRS release branch (copy of trunk) configuration we noticed issues with rest client reading response entity.

Code to reproduce:
```
getRestClient(superuser)
        .attributesService()
        .attribute(emptyValueAttribute.getName())
        .setIncludePermissions(true)
        .createOrUpdate(emptyValueAttribute)
        .getSerializedContent();
```

Where emptyValueAttribute is:

```
<?xml version="1.0" encoding="UTF-8"?>
<bean id="administerAttribute" class="com.jaspersoft.jasperserver.dto.authority.hypermedia.HypermediaAttribute">
   <property name="name" value="administerAttribute" />
   <property name="value" value= null />
   <property name="description" value="Administer Attribute description" />
   <property name="permissionMask" value="1" />
   <property name="secure" value="false" />
   <property name="inherited" value="false" />
   <property name="holder" value="tenant:/" />
   <property name="embedded" ref="administerPermissionContainer" />
</bean>
```

This code will return null. But it is expected to return
```
{  
   "message":"The value \"null\" for parameter \"value\" is invalid.",
   "errorCode":"illegal.parameter.value.error",
   "parameters":[  
      "value",
      null
   ]
}
```

When execute the request manually:

`PUT {JRS_URL}/rest_v2/attributes/administerAttribute_00278?_embedded=permission`

```
Accept: application/hal+json
Content-Type: application/hal+json

```

```
{  
   "name":"administerAttribute_00278",
   "value":null,
   "secure":false,
   "inherited":false,
   "description":"Administer Attribute description_00278",
   "permissionMask":1,
   "holder":"tenant:/",
   "_embedded":{  
      "permission":[  
         {  
            "recipient":"role:/ROLE_ADMINISTRATOR",
            "mask":1
         }
      ]
   }
}
```

It returns correct response:

```
{
"message": "The value "null" for parameter "value" is invalid."
"errorCode": "illegal.parameter.value.error"
"parameters": [2]
0:  "value"
1:  null
-
}
```

**Comment by TanyaEf** [comment]
In this case client works in right way, because by default the client handle all server's responses equal or greater 400 and throws exceptions before creating operation result instance. To get operation result with serialized content you should turn of exception handling using `configuration.setHandleErrors(false);` property(look in the documentation https://github.com/Jaspersoft/jrs-rest-java-client#exception-handling)  like in this example:
```java
     RestClientConfiguration  configuration = RestClientConfiguration.loadConfiguration(properties);
     JasperserverRestClient client = new JasperserverRestClient(configuration);
     configuration.setHandleErrors(false);
     Session session = client.authenticate(username, password);
     
     OperationResult<HypermediaAttribute> operationResult = session
                    .attributesService()
                    .attribute(attribute.getName())
                    .setIncludePermissions(true)
                    .createOrUpdate(attribute);
        String massage  = operationResult.getSerializedContent();
```

**Comment by leonidbondar** [comment]
We have handleErrors parameter set to false in our configuration of rest client:

```
<?xml version="1.0" encoding="UTF-8"?>
<bean id="restClientConfiguration" class="com.jaspersoft.jasperserver.jaxrs.client.core.RestClientConfiguration">
   <property name="jasperReportsServerUrl" value="#{jrsUrl}" />
   <property name="acceptMimeType" value="JSON" />
   <property name="contentMimeType" value="JSON" />
   <property name="handleErrors" value="false" />
   <property name="logHttp" value="true" />
   <property name="logHttpEntity" value="true" />
</bean>
```

and we are able to get operation result with these settings normally on the majority of JRS configurations. 
The problem with creating operation result we have is specific to WildFly 8.2.1.

**Comment by TanyaEf** [comment]
Could you please provide the log of HTTP requests and responces?

**Comment by leonidbondar** [comment]
I can no longer reproduce this issue on latest JRS trunk build.
However, there is another issue I logged which can be reproduced on the variety of Wildflys. 
Please take a look: https://github.com/Jaspersoft/jrs-rest-java-client/issues/201

Closing this one.

**Comment by leonidbondar** [comment]
I've clarified that it is the same issue as https://github.com/Jaspersoft/jrs-rest-java-client/issues/201

At the time this issue originally occurred we didn't have logHttp and logHttpEntity properties of the rest-client enabled, so we didn't get Too many "Content-Type" header values ... exception and considered operation to be finished successfully and were getting null when trying getSerializedContent.
This confused me into thinking we have two different bugs.

When logs are enabled we get Too many header values exception. 
Log of HTTP requests and responses are provided in this bug https://github.com/Jaspersoft/jrs-rest-java-client/issues/201
