### ISSUE TITLE
import with update parameter set to true doesn't update a resource

### ISSUE THREAD

**Issue by leonidbondar** [Jaspersoft/jrs-rest-java-client#190]
1. Import a resource via import service with ImportParameter.UPDATE set to true
```
getRestClient()
                            .authenticate(superuser.getUsername(), superuser.getPassword())
                            .importService()
                            .newTask()
                            .parameter(ImportParameter.UPDATE, true)
                            .create(importCatalog);
```
2. Make some changes to the file (i.e.: change description)
3. Run import request from step 1 again

Result: changes made in step 2 aren't overridden, resource isn't updated.

**Comment by TanyaEf** [comment]
Sorry, but I can't reproduce this bug, I've tried with resources like as domain and folder and in the both cases import with RestClent works fine. Here are my steps:

1. create resource on the server
2. export it to local file system
3. change description
4. import from local file system to server using next code:

```java
File zipArchive = new File("d:\\workspaceIdea\\exportedDomains\\folder.zip");


        OperationResult<State> operationResult = session
                .importService()
                .newTask()
                .parameter(ImportParameter.INCLUDE_ACCESS_EVENTS, true)
                .parameter(ImportParameter.UPDATE, true)
                .create(zipArchive);

        State stateDto = operationResult.getEntity();

        while (stateDto.getPhase().equals(INPROGRESS_STATUS)) {
            stateDto = session
                    .importService()
                    .task(stateDto.getId())
                    .state().getEntity();
            Thread.sleep(100);
        }
```

And my resources have source description (set before export)/ You can find screenshots attached. My environment:
JasperReportsServer 6.2.0
Apache Tomcat/8.0.14
JavaRestClient 6.2.1
![start](https://cloud.githubusercontent.com/assets/8988631/14563171/3affd946-0329-11e6-8d94-76343b80f851.jpg)
![second](https://cloud.githubusercontent.com/assets/8988631/14563170/3ad5bc24-0329-11e6-9b6d-49e829bda7eb.jpg)
![after_update](https://cloud.githubusercontent.com/assets/8988631/14563169/3abcd376-0329-11e6-90be-7660b72c4573.jpg)

**Comment by leonidbondar** [comment]
Verified issue is no longer reproducible on trunk Build 20160415_1708

Importing with parameters:
```
    session
                            .importService()
                            .newTask()
                            .parameter(ImportParameter.UPDATE, true)
                            .parameter(ImportParameter.INCLUDE_SERVER_SETTINGS, true)
                            .parameter(ImportParameter.INCLUDE_ACCESS_EVENTS, true)
                            .parameter(ImportParameter.INCLUDE_AUDIT_EVENTS, true)
                            .parameter(ImportParameter.INCLUDE_MONITORING_EVENTS, true)
                            .create(importCatalog);
```
