### ISSUE TITLE
Add configuration to set connection timeout

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#192]
It might happen that JRS hangs and when you request it it neither respond with error or with positive result. For such situations we need to set connection timeout for the client

**Comment by TanyaEf** [comment]
You can try to set connection timeout before getting JasperserverRestClient instance :
```java
RestClientConfiguration configuration = new RestClientConfiguration("http://localhost:4444/jasperserver");
configuration.setConnectionTimeout(2500);// value of connection time out in milliseconds
JasperserverRestClient client = new JasperserverRestClient(configuration);
```
