### ISSUE TITLE
Parameter Type Support

### ISSUE THREAD

**Issue by TestOverload** [Jaspersoft/jrs-rest-java-client#20]
Hi,
  My report contains some Date type parameters. When my program run the report in jasper server, for example:
OperationResult<InputStream> result = client
        .authenticate("jasperadmin", "jasperadmin")
        .reportingService()
        .report("/reports/samples/Cascading_multi_select_report")
        .prepareForRun(ReportOutputFormat.HTML, 1)
        .parameter("Cascading_name_single_select", "A & U Stalker Telecommunications, Inc")
        .run();
InputStream report = result.getEntity();

I found that only String type data can be assigned. Can you add more data type support? Or is there any way to make the report receive Date Type parameters etc?

**Comment by dilippatidar123** [comment]
Hi,
I am using the jrs-rest-java-client 6.3.0 Version.
I want to pass date parameter as date time stamp.
Example :-  
      ```
OperationResult<InputStream> result = session
                .reportingService()
                .report("/reports/TESTREPORT")
                .prepareForRun(ReportOutputFormat.XLS, 1)
                .parameter("startdate",datetime)
                .parameter("enddate", datetime)

        .parameter("ordertype","Test")
                .run();
```
RunReportAdapter class has only 2 method.
```

` public com.jaspersoft.jasperserver.jaxrs.client.apiadapters.reporting.RunReportAdapter parameter(java.lang.String name, java.lang.String... value) { /* compiled code */ }`

    public com.jaspersoft.jasperserver.jaxrs.client.apiadapters.reporting.RunReportAdapter parameter(java.lang.String name, java.util.List<java.lang.String> values) { /* compiled code */ }
```

Please Suggest.
Thanks in Advance.

Regards,
Dilip
