### ISSUE TITLE
DTO: Setters of Scheduler job dto package return void

### ISSUE THREAD

**Issue by leonidbondar** [Jaspersoft/jrs-rest-java-client#204]
com.jaspersoft.jasperserver.jaxrs.client.dto.jobs package has setters which return void. 
Set methods should return class instance.

Please refer to QA Automation - QAA Requirements for Dev (Deprecated)
http://wiki.jaspersoft.com/pages/viewpage.action?pageId=49318126
"all client dtos should have equals, toString, hashcode, builder pattern (all setters should return this)"

**Comment by TanyaEf** [comment]
Fixed in 6.2.4 version
