### ISSUE TITLE
DTO: jobs getTrigger method returns instance of JobTriggerclass, it's not possible to determine either SimpleTrigger or CalendarTrigger does the job have

### ISSUE THREAD

**Issue by leonidbondar** [Jaspersoft/jrs-rest-java-client#205]
com.jaspersoft.jasperserver.jaxrs.client.dto.jobs package classes
don't have setters and getters for every property.
For example JobTrigger class doesn't have getters and setters for: occurrenceCount, recurrenceInterval, recurrenceIntervalUnit
It's expected that properties have getters and setters

**Comment by TanyaEf** [comment]
JobTrigger is abstract class, you can't instantiate it anyway. You should use its extension com.jaspersoft.jasperserver.jaxrs.client.dto.jobs.SimpleTrigger, where there are these properties and theirs getters/setters.

**Comment by leonidbondar** [comment]
Could you please advise on how I should work with instance of job object: 

I have assertions for a job and need to pass there expected values, I need to replace hard-coded values with properties of my test job, however `getTrigger() `method returns instance of `JobTrigger `class so private properties of it's descendants (`SimpleTrigger `or `CalendarTrigger`) can not be accessed
` Job job = new Job();`
 `job.getTrigger().getStartType(); `
- is valid, `startType `is defined for `JobTrigger `
` job.getTrigger().getRecurrenceIntervalUnit() `- won't be possible because `getRecurrenceIntervalUnit `isn't defined for `JobTrigger `but only for `SimpleTrigger`.
We need a way to get these properties from the job object

**Comment by yaroslav-kovalchyk** [comment]
Please check for instanceof and then cast trigger to concrete class like this:
```
JobTrigger trigger = job.getTrigger();
if(trigger instanceof SimpleTrigger){
    SimpleTrigger simpleTrigger = (SimpleTrigger)trigger;
    Byte recurrenceIntervalUnit = simpleTrigger.getRecurrenceIntervalUnit();
}
```
