### ISSUE TITLE
Scheduler: Job class of client.dto doesn't have baseOutputFileDescription property

### ISSUE THREAD

**Issue by leonidbondar** [Jaspersoft/jrs-rest-java-client#207]
class Job of package com.jaspersoft.jasperserver.jaxrs.client.dto.jobs doesn't have property which would represent OutputFile description. It only has baseOutputFilename.

Thus, it's not possible to create a job using rest client which would have outputFile description other than null.

**Comment by TanyaEf** [comment]
Sorry, but server doesn't support such functionality, so we can't add such property to the DTO. May be appropriate enhancement should be implemented on server firstly.

**Comment by leonidbondar** [comment]
Tanya, how can you see that  "server doesn't support such functionality"?
It is possible to create job on UI which would generate output with description. outputDescription property is used to pass description inputted on Output Options tab http://screencast.com/t/bE9SFTJSVe

Also it is posible to create such job via rest, try the following request:

```
{JRS_URL}/rest_v2/jobs

authorization: superuser/superuser
Accept: application/job+json
Content-Type: application/job+json

Request body:

{  
   "id":null,
   "version":null,
   "username":null,
   "label":"Calendar recurrence rest job with default recurrence settings_22a0b",
   "description":"Every moth, every day job with default times schedule",
   "creationDate":null,
   "baseOutputFilename":"Report_output_test_072b1",
   "outputLocale":null,
   "repositoryDestination":{  
      "folderURI":"/public",
      "id":null,
      "outputDescription":"test output description",
      "overwriteFiles":null,
      "sequentialFilenames":null,
      "version":null,
      "timestampPattern":null,
      "saveToRepository":true,
      "defaultReportOutputFolderURI":null,
      "usingDefaultReportOutputFolderURI":null,
      "outputLocalFolder":null,
      "outputFTPInfo":null
   },
   "source":{  
      "reportUnitURI":"/public/Samples/Reports/08.UnitSalesDetailReport",
      "parameters":null
   },
   "outputFormats":{  
      "outputFormat":[  
         "CSV",
         "HTML"
      ]
   },
   "trigger":{  
      "simpleTrigger":{  
         "id":133302,
         "version":0,
         "timezone":"America/Los_Angeles",
         "startType":1,
         "misfireInstruction":0,
         "occurrenceCount":-1,
         "recurrenceInterval":1,
         "recurrenceIntervalUnit":"DAY"
      }
   },
   "outputTimeZone":null
}
```

This would create two Report_output_test_072b1 output files in /public with not empty description

**Comment by TanyaEf** [comment]
I was confused with " baseOutputFilename" property. The property "outputDescription" present in `com.jaspersoft.jasperserver.jaxrs.client.dto.jobs.RepositoryDestination` (according to documentation http://wiki.jaspersoft.com/display/7XX/Scheduling#Scheduling-EntityDesctiption:repositoryDestination
 `The description to be used for job output resources. The description will be used as is for all output resources.`

You can set it using getter of `com.jaspersoft.jasperserver.jaxrs.client.dto.jobs.Job` object, something like this:
```
 new Job().setRepositoryDestination(new RepositoryDestination().setOutputDescription("test output description"));
```
