### ISSUE TITLE
ClientRole is not deserialised correctly when get entity after create/update role

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#233]
Test to reproduce: should_create_role and should_update_role

Steps:

OperationResult<ClientRole> result = session
                .rolesService()
                .roleName(testRole.getName())
                .createOrUpdate(testRole);
       result.getEntity() >> would return role with null name and tennant id, while HTTP response is correct

**Comment by TanyaEf** [comment]
This bug is caused by wrong response format (array in JSON instead of single value), so I think issue may be closed.
