### ISSUE TITLE
Bad compiler configuration in pom.xml

### ISSUE THREAD

**Issue by nicolaslledosnef** [Jaspersoft/jrs-rest-java-client#234]
Source and Target configuration in the maven-compiler-plugin entry of the pom.xml are set to 1.6.
With this value, you won't be able to build because com.jaspersoft.jasperserver.jaxrs.client.dto.jobs.JobTrigger.deepClone() raises a ReflectiveOperationException. This exception exists since jdk 1.7.
See https://docs.oracle.com/javase/7/docs/api/java/lang/ReflectiveOperationException.html

Changing the configuration by setting 1.7 solves the problem.

**Comment by TanyaEf** [comment]
Fix available in develop branch and will be included to nearest release.
