### ISSUE TITLE
Basic authentication with locale is not implemented yet

### ISSUE THREAD

**Issue by DevHammer2016** [Jaspersoft/jrs-rest-java-client#235]
Running a report with 'ReportingService' logged in with basic authentication results always in an english report.
The locale set on authentication is not considered.

i.e.
client.authenticate("jasperadmin", "jasperadmin", new Locale("de"), TimeZone.getTimeZone( "Europe/Berlin" ));

**Comment by DevHammer2016** [comment]
Setting authenticationType to HTTP works!

**Comment by TanyaEf** [comment]
For ReportService you can set time zone and locale for particular request using the code below:

```java
        OperationResult<InputStream> result = session
                .reportingService()
                .report("/public/Samples/Reports/12g.PromotionDetailsReport")
                .prepareForRun(ReportOutputFormat.PDF, 1)
                .forTimeZone(TimeZone.getTimeZone("America/Los_Angeles"))
                .parameter("userLocale", "de")
                .run();
```
