### ISSUE TITLE
InputControl's dataType reference is not present on UI

### ISSUE THREAD

**Issue by cfe112tt826a** [Jaspersoft/jrs-rest-java-client#236]
Steps:
1. Create any datatype.
2. Create "Single Value" Input Control with newly created datatype.
3. Login to JRS from UI, open Repository page
4. Edit the input control, click Next.
Expected result: "Select a Datatype from the repository" radio button selected and /public/repositoryDataType uri present (http://screencast.com/t/JqhoY64o5nxE)
Actual result: "Define a Datatype in the next step" selected (http://screencast.com/t/9UFIEogW)

Code to reproduce from JRS client:

        JasperserverRestClient restClient = new JasperserverRestClient(restClientConfiguration);
        Session session = restClient
                .authenticate("superuser", "superuser");

         // create datatype
         ClientDataType repositoryDataType = new ClientDataType()
                .setType(ClientDataType.TypeOfDataType.text)
                .setPattern("~t")
                .setLabel("repositoryDataType")
                .setUri("/public/repositoryDataType");

        session
                .resourcesService()
                .resource(repositoryDataType.getUri())
                .createOrUpdate(repositoryDataType);

        // create input control
        byte singleInputValue = 2;
        ClientInputControl inputControl = new ClientInputControl()
                .setLabel("inputControl")
                .setDataType(repositoryDataType)
                .setType(singleInputValue)
                .setUri("/public/inputControl");

        session
                .resourcesService()
                .resource(inputControl.getUri())
                .createOrUpdate(inputControl);

Everything works fine from any other rest client:
PUT: http://localhost:8080/jasperserver-pro/rest_v2/resources/public/inputControl
Content-Type: application/repository.inputControl+json
Accept: application/json
Body:
{
    "label" : "inputControl",
    "version" : 0,
    "uri" : "/public/inputControl",
   "mandatory":"false",
   "readOnly":"false",
   "visible":"false",
   "type":"2",
   "dataType":{
      "dataTypeReference":{
         "uri":"/public/repositoryDataType"
      }
   }
}

**Comment by tmatveyeva** [comment]
Yaroslav, in order to create IC with datatype from repository, you must set ClientReference as a datatype. You created internal datatype and it worked as expected. 

This should work for external resource

ClientInputControl inputControl = new ClientInputControl()
            .setLabel("inputControl")
            .setDataType(new ClientReference({DATATYPE URI}))
            .setType(singleInputValue)
            .setUri("/public/inputControl");
