### ISSUE TITLE
Provide a way to get jersey client to be able to test negative cases or clear json

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#242]
After we authenticate to JRS via REST client, please provide a way to retrieve plain jersey client with session in order to test negative cases or work with plain JSON, without using DTO objects

It will be required for domain metadata testing for the beginning, so we need implementation in that branch.

**Comment by TanyaEf** [comment]
Available in develop and develop-domainDesigner branches
