### ISSUE TITLE
develop branch: unable to create user in organization

### ISSUE THREAD

**Issue by YaroslavKhrushch** [Jaspersoft/jrs-rest-java-client#257]
Try to submit the following request:
new JasperserverRestClient(restClientConfiguration)
                    .authenticate("superuser", "superuser")
                    .usersService()
                    .forOrganization("organization_1")
                    .user(user.getUsername())
                    .createOrUpdate(user);
Expected: 201 Created; new user in organization_1 is created
Actual: 400 Bad Request; {"message":"The value \"organization_1\" for parameter \"tenantId\" is invalid.","errorCode":"illegal.parameter.value.error","parameters":["tenantId","organization_1"]} 

Everything works fine when creating user in root

**Comment by TanyaEf** [comment]
Bugfix is available in develop branch
