### ISSUE TITLE
It should be possible to create organization when only alias specified (id can be null)

### ISSUE THREAD

**Issue by YaroslavKhrushch** [Jaspersoft/jrs-rest-java-client#261]
Steps in Advanced Rest Client:
As superuser POST http://localhost:8080/jasperserver-pro/rest_v2/organizations
Content-Type: application/json
Body:
{
    "alias" : "alias"
}
Actual result: 201 Created

Actual result in jrs-rest-java-client: IllegalArgumentException("Organization is not valid.");

**Comment by TanyaEf** [comment]
Bugfix is available in develop branch
