### ISSUE TITLE
It shouldn't be possible to create organizations with slashes in alias

### ISSUE THREAD

**Issue by YaroslavKhrushch** [Jaspersoft/jrs-rest-java-client#262]
ClientTenant testOrg = new ClientTenant().setId("id").setAlias("Bad/\\alias");
session
                    .organizationsService()
                    .organization(testOrg)
                    .create();
Expected result: 400 bad request
Actual result: 201 created, organization is created with alias "Bad/\alias"

Actual result via Advanced Rest Client is 500 Internal Server Error.

**Comment by tmatveyeva** [comment]
I don't think this is issue of the client. Please check what is client is actually sending (enable http logging) and I'm sure if you do the same manually you will get same result
