### ISSUE TITLE
Incorrect Accept header sent for resources service

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#264]
When I try to get new Domain descriptor (ClientDomain class)

getRestClient(jasperadmin)
                .resourcesService()
                .resource("/qa_automation/Domain/changedField")
                .get(ClientDomain.class);

Accept type sent by client is 
2 > Accept: application/repository.file+json

as a result retrieved descriptor is old SemanticLayerDataSource
Content-Type: application/repository.semanticLayerDataSource+json

Rest client should send correct Accept type depending on type of the resource we try to retrieve
in example above it is Accept: application/repository.domain+json

**Comment by TanyaEf** [comment]
Fix is available in develop branch
