### ISSUE TITLE
Update jrxml file

### ISSUE THREAD

**Issue by salk31** [Jaspersoft/jrs-rest-java-client#268]
Hello,

I'm probably missing something obvious but I can't see how to update an already uploaded file (using uploadFile method).

I tried delete/uploadFile but some of the jrxml is locked by being used for a report.

Many thanks

Sam

**Comment by gt78** [comment]
Is this a single resource or a resource part of a report unit?

**Comment by salk31** [comment]
I was just trying to do single resources but if I could update any part of a report unit I could switch to that.

**Comment by salk31** [comment]
FWIW I cobbled something together something using patch but it is quite verbose.

**Comment by gt78** [comment]
What do you mean with patch? The point is that you should not recreate the resource, but just modify the existing resource providing the new data.

**Comment by salk31** [comment]
```
            PatchDescriptor patchDescriptor = new PatchDescriptor();
            patchDescriptor.setVersion(version.intValue());
            patchDescriptor.field("content", encodedString);

            OperationResult<ClientFile> result = client
                    .authenticate("XXX", "XXX").resourcesService()
                    .resource(getFinalPath())
                    .patchResource(ClientFile.class, patchDescriptor);
```

So works but a bit of a pain as I also need to fetch the version?

**Comment by gt78** [comment]
Yes, this is the correct way of doing it.

**Comment by salk31** [comment]
Ah OK. Is the uploadFile just a convenience method? Cleaner to use the other repository methods?

I got confused because the API docs seem to suggest updateFile could/should exist http://community.jaspersoft.com/documentation/tibco-jasperreports-server-rest-api-reference/v621/working-file-resources#Updating_File_Resources

Anyway, thanks for your time.

**Comment by gt78** [comment]
It is not about uploading a generic file but a specific type of resource (FileResource)

**Comment by salk31** [comment]
OK. Many thanks.
