### ISSUE TITLE
Provide specific Accept header when create resource

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#271]
When try to create resource:

ClientDomain testDomain = ... (valid test domain here);
Session session = ... (valid session under any user here);

        OperationResult<ClientResource> createResponse = session
                .resourcesService()
                .resource("/test/folder")
                .createNew(testDomain);

The following request is performed:

21 Dec 2016 15:57:30  INFO SessionStorage - 2 * Sending client request on thread main
2 > POST http://localhost:8080/jasperserver-pro/rest_v2/resources/qa_automation/Domain/Post
2 > Accept: application/json
2 > Content-Type: application/repository.domain+json

You can see that Accept header is generic "application/json". Can you please fix it to be same as content type?

**Comment by TanyaEf** [comment]
Fix is available in develop brunch
