### ISSUE TITLE
Impossible to login to JRS under anounymousUser

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#274]
In authentication method in REST client there is following check:

    public Session authenticate(String username, String password, Locale userLocale, TimeZone userTimeZone) {
        if(username != null && username.length() > 0 && password != null && password.length() > 0) {

However, password can be empty and it is empty for anonymousUser

**Comment by TanyaEf** [comment]
Fix is available in develop branch
