### ISSUE TITLE
create domain returns bad request

### ISSUE THREAD

**Issue by venkatachalama** [Jaspersoft/jrs-rest-java-client#296]
### public void createDomain() {
        appLogger.info("Start to create domain with single data island.");
        OperationResult<ClientDomain> operationResult = configuration.getSession()
                .domainService()
                .domain(configuration.getBaseRepositoryFolder())
                .create(InitDataHelper.fetchDomain(configuration.getBaseRepositoryFolder(),
                        "New_domain",
                        "/public/Samples/Data_Sources/FoodmartDataSourceJNDI"));
        int status = operationResult.getResponse().getStatus();
        if (status >= 400) {
            appLogger.warn("Error of creating domain. Error code: " + status);
            System.exit(0);
        }
        appLogger.info( operationResult.getEntity().getLabel() + " was created successful");
        appLogger.info("Domain was created successful");
    }
### public static ClientDomain fetchDomain(String baseFolder, String domainName, String dataSourceUri) {
        appLogger.info("Start to create domain");
        ClientDomain domain = new ClientDomain().
                setUri(baseFolder + "/" + domainName).
                setLabel(domainName).
                setDataSource(new ClientReference().setUri(dataSourceUri)).
                setSchema(fetchSchema());
        return domain;
    }

## 2017-05-26 16:45:47,476 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 2 * Sending client request on thread main
2 > POST http://192.168.120.29:80/jasperserver-pro/rest_v2/resources/public/DomainDemo
2 > Accept: application/json
2 > Content-Type: application/repository.domain+json

### 017-05-26 16:45:47,488 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 2 * Client response received on thread main
2 < 400
2 < Connection: close
2 < Content-Type: application/errorDescriptor+json
2 < Date: Wed, 24 May 2017 05:42:22 GMT
2 < P3P: CP="ALL"
2 < Server: Apache-Coyote/1.1
2 < Set-Cookie: userLocale=en_US;Expires=Thu, 25-May-2017 05:42:22 GMT;Path=/jasperserver-pro/;HttpOnly,JSESSIONID=631D2D86D0B565C86F14BE6616EEDAF5; Path=/jasperserver-pro/; HttpOnly
2 < Transfer-Encoding: chunked
{"message":"The value \"null\" for parameter \"Content-Disposition\" is invalid.","errorCode":"illegal.parameter.value.error","parameters":["Content-Disposition",null]}

**Comment by yaroslav-kovalchyk** [comment]
Hello. ClientDomain DTO is a part of released JasperServer, but server side handlers are still under development. I agree, that this error descriptor looks confusing, but you'll not be able to create domain using ClientDomain DTO any way. Please use ClientSemanticLayerDataSource for now.

**Comment by venkatachalama** [comment]
Thanks for the fast response.
Can you please provide any sample code using ClientSemanticLayerDataSource  for creating domain.

**Comment by yaroslav-kovalchyk** [comment]
Unfortunately I can't provide a sample just away... Please create another issue about lack of sample how to create semanticLayerDataSource resource type and I'll provide a sample later.
