### ISSUE TITLE
Build error for develop branch code

### ISSUE THREAD

**Issue by venkatachalama** [Jaspersoft/jrs-rest-java-client#300]
[INFO] Building REST client for JasperReports server 6.3.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: http://mvnrepo.jaspersoft.com:8081/artifactory/repo/com/jaspersoft/jasperserver/jasperserver-dto/trunk-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: http://repository.opencastproject.org/nexus/content/repositories/public/com/jaspersoft/jasperserver/jasperserver-dto/trunk-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.jaspersoft.jasperserver:jasperserver-dto:trunk-SNAPSHOT/maven-metadata.xml from/to opencast-public (http://repository.opencastproject.org/nexus/content/repositories/public): connect timed out
[WARNING] Could not transfer metadata com.jaspersoft.jasperserver:jasperserver-dto:trunk-SNAPSHOT/maven-metadata.xml from/to artifactory_ua (http://mvnrepo.jaspersoft.com:8081/artifactory/repo): mvnrepo.jaspersoft.com
[WARNING] Failure to transfer com.jaspersoft.jasperserver:jasperserver-dto:trunk-SNAPSHOT/maven-metadata.xml from http://repository.opencastproject.org/nexus/content/repositories/public was cached in the local repository, resolution will not be reattempted until the update interval of opencast-public has elapsed or updates are forced. Original error: Could not transfer metadata com.jaspersoft.jasperserver:jasperserver-dto:trunk-SNAPSHOT/maven-metadata.xml from/to opencast-public (http://repository.opencastproject.org/nexus/content/repositories/public): connect timed out
[WARNING] Failure to transfer com.jaspersoft.jasperserver:jasperserver-dto:trunk-SNAPSHOT/maven-metadata.xml from http://mvnrepo.jaspersoft.com:8081/artifactory/repo was cached in the local repository, resolution will not be reattempted until the update interval of artifactory_ua has elapsed or updates are forced. Original error: Could not transfer metadata com.jaspersoft.jasperserver:jasperserver-dto:trunk-SNAPSHOT/maven-metadata.xml from/to artifactory_ua (http://mvnrepo.jaspersoft.com:8081/artifactory/repo): mvnrepo.jaspersoft.com
[INFO] Downloading: http://jaspersoft.artifactoryonline.com/jaspersoft/jrs-ce-releases/com/jaspersoft/jasperserver/jasperserver-dto/trunk-SNAPSHOT/jasperserver-dto-trunk-SNAPSHOT.pom
[INFO] Downloading: http://repository.opencastproject.org/nexus/content/repositories/public/com/jaspersoft/jasperserver/jasperserver-dto/trunk-SNAPSHOT/jasperserver-dto-trunk-SNAPSHOT.pom
[INFO] Downloading: http://mvnrepo.jaspersoft.com:8081/artifactory/repo/com/jaspersoft/jasperserver/jasperserver-dto/trunk-SNAPSHOT/jasperserver-dto-trunk-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.803 s
[INFO] Finished at: 2017-05-30T15:09:04+05:30
[INFO] Final Memory: 9M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jrs-rest-java-client: Could not resolve dependencies for project com.jaspersoft:jrs-rest-java-client:jar:6.3.4-SNAPSHOT: Failed to collect dependencies at com.jaspersoft.jasperserver:jasperserver-dto:jar:trunk-SNAPSHOT: Failed to read artifact descriptor for com.jaspersoft.jasperserver:jasperserver-dto:jar:trunk-SNAPSHOT: Could not transfer artifact com.jaspersoft.jasperserver:jasperserver-dto:pom:trunk-SNAPSHOT from/to jrs-ce-releases (http://jaspersoft.artifactoryonline.com/jaspersoft/jrs-ce-releases/): Failed to transfer http://jaspersoft.artifactoryonline.com/jaspersoft/jrs-ce-releases/com/jaspersoft/jasperserver/jasperserver-dto/trunk-SNAPSHOT/jasperserver-dto-trunk-SNAPSHOT.pom. Error code 409, Conflict.
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Hello, When i am building develop branch code of jrs-rest-java-client. It is throwing builld error.
Please find the log attached..

**Comment by yaroslav-kovalchyk** [comment]
Develop branch is using our internal artifacts (not released yet). Please use released version of client.

**Comment by venkatachalama** [comment]
Hi 
If released version full-domain-api2-SHAPSHOT has support for domain designer, please let know the procedure. Actually i had an urgent requirement to create domain design in jasper server using client.
It would be grateful, if u give a sample.

**Comment by yaroslav-kovalchyk** [comment]
Released version of JasperRerportsServer supports only getting domain metadata (beta version). All the rest functionality related to domain designer is still under development (available internally only).

**Comment by venkatachalama** [comment]
Can you please provide any other approach to create domain designer, if client library is not supporting.

**Comment by yaroslav-kovalchyk** [comment]
I'll provide a sample in scope of https://github.com/Jaspersoft/jrs-rest-java-client/issues/297
