### ISSUE TITLE
error while creating domain using ClientSemanticLayerDataSource

### ISSUE THREAD

**Issue by venkatachalama** [Jaspersoft/jrs-rest-java-client#301]
## public void createBaseDomain() {
        appLogger.info("Start to create domain with single data island on the server...");
        // create base domain
        ClientSemanticLayerDataSource baseDomain = InitDomainHelper.buildDomain(configuration.getBaseRepositoryFolder(),
                "Base_domain",
                DATA_SOURCE_URI);
        
        // save domain on the server
        saveDomain(baseDomain);

    }
## private void saveDomain(ClientSemanticLayerDataSource baseDomain) {	
    	OperationResult<ClientSemanticLayerDataSource> operationResult = session.resourcesService().resource(baseDomain).
    	      withSchema(InitDomainHelper.buildSchema().toString(), 
    			         new ClientFile().setLabel("baseDomain_schema").
    			                          setDescription("baseDomain_schema").
    			                      
                                         setType(FileType.xml)).createInFolder(configuration.getBaseRepositoryFolder());
    	
        int status = operationResult.getResponse().getStatus();
        
        if (status >= 400) {
            appLogger.warn("Error of creating domain. Error code: " + status + "response : " + operationResult.getResponse().getHeaders());
            appLogger.warn("Error of creating domain. Error code: " + operationResult.getResponseStatus());
            consoleLogger.info("Delete demonstration resources?[y/n]: ");

            deleteBaseFolder(ConsoleUtil.readChar(new Character[]{'y', 'n'}) == 'y');
            stopApplication();
            System.exit(1);
        }
        appLogger.info(operationResult.getEntity().getLabel() + " was created on the server successfully");
        appLogger.info("Domain was created successful");
    }

# ## Error: 
2 > POST http://192.168.120.29:80/jasperserver-pro/rest_v2/resources/public/DomainDemo
2 > Accept: application/json
2 > Content-Type: multipart/form-data
--Boundary_1_986317581_1496917329819
Content-Type: application/xml
Content-Disposition: form-data; name="schema"

Schema{resources=[ResourceGroupElement{type='null'} AbstractResourceGroupElement{elements=[ResourceGroupElement{type='null'} AbstractResourceGroupElement{elements=[ResourceGroupElement{type='null'} AbstractResourceGroupElement{elements=[AbstractResourceSingleElement{type='java.lang.String', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='address'}, AbstractResourceSingleElement{type='java.lang.Integer', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='empid'}, AbstractResourceSingleElement{type='java.lang.String', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='name'}], filterExpression='null'} ResourceElement{sourceName='t1'} SchemaElement{name='public_t1'}, ResourceGroupElement{type='null'} AbstractResourceGroupElement{elements=[AbstractResourceSingleElement{type='java.lang.String', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='country'}, AbstractResourceSingleElement{type='java.lang.String', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='division'}, AbstractResourceSingleElement{type='java.lang.Integer', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='empid'}, AbstractResourceSingleElement{type='java.lang.Integer', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='libid'}, AbstractResourceSingleElement{type='java.lang.String', expression='null'} ResourceElement{sourceName='null'} SchemaElement{name='salary'}], filterExpression='null'} ResourceElement{sourceName='public_t2'} SchemaElement{name='public_t2'}], filterExpression='null'} ResourceElement{sourceName='public'} SchemaElement{name='schema1'}], filterExpression='null'} ResourceElement{sourceName='null'} SchemaElement{name='MysqlDataSource'}, JoinResourceGroupElement{joinInfo=JoinInfo{includeAllJoinsForQueryFieldTables=null, includeAllDataIslandJoins=false, suppressCircularJoins=false, joins=[Join{left='public_t1', right='public_t2', expression='ClientExpressionContainer{object=null, string='public_t1.empid == public_t2.empid'}', weight=1, type=inner}], mandatoryTables=null}} AbstractResourceGroupElement{elements=[ReferenceElement{referencePath='MysqlDataSource.schema1.public_t2'} SchemaElement{name='public_t2'}, ReferenceElement{referencePath='MysqlDataSource.schema1.public_t1'} SchemaElement{name='public_t1'}], filterExpression='null'} ResourceElement{sourceName='null'} SchemaElement{name='JoinTree_1'}], presentation=[PresentationGroupElement{elements=[PresentationGroupElement{elements=[PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.String', hierarchicalName='public_t1.address', resourcePath='JoinTree_1.public_t1.address'} PresentationElement{label='address', labelId='', description='address', descriptionId=''} SchemaElement{name='address'}, PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.Integer', hierarchicalName='public_t1.empid1', resourcePath='JoinTree_1.public_t1.empid'} PresentationElement{label='empid', labelId='', description='empid1', descriptionId=''} SchemaElement{name='empid1'}, PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.String', hierarchicalName='public_t1.name', resourcePath='JoinTree_1.public_t1.name'} PresentationElement{label='name', labelId='', description='name', descriptionId=''} SchemaElement{name='name'}], kind='null'} PresentationElement{label='public_t1', labelId='', description='public_t1', descriptionId=''} SchemaElement{name='public_t1'}, PresentationGroupElement{elements=[PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.String', hierarchicalName='public_t2.country', resourcePath='JoinTree_1.public_t2.country'} PresentationElement{label='country', labelId='', description='country', descriptionId=''} SchemaElement{name='country'}, PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.String', hierarchicalName='public_t2.division', resourcePath='JoinTree_1.public_t2.division'} PresentationElement{label='division', labelId='', description='division', descriptionId=''} SchemaElement{name='division'}, PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.Integer', hierarchicalName='public_t2.empid', resourcePath='JoinTree_1.public_t2.empid'} PresentationElement{label='empid', labelId='', description='empid', descriptionId=''} SchemaElement{name='empid'}, PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.Integer', hierarchicalName='public_t2.libid', resourcePath='JoinTree_1.public_t2.libid'} PresentationElement{label='libid', labelId='', description='libid', descriptionId=''} SchemaElement{name='libid'}, PresentationSingleElement{maskId='null', mask='null', aggregation='null', kind=null, type='java.lang.String', hierarchicalName='public_t2.salary', resourcePath='JoinTree_1.public_t2.salary'} PresentationElement{label='salary', labelId='', description='salary', descriptionId=''} SchemaElement{name='salary'}], kind='null'} PresentationElement{label='public_t2', labelId='', description='public_t2', descriptionId=''} SchemaElement{name='public_t2'}], kind='null'} PresentationElement{label='null', labelId='null', description='null', descriptionId='null'} SchemaElement{name='JoinTree_1'}]}
--Boundary_1_986317581_1496917329819
Content-Type: application/repository.semanticlayerdatasource+json
Content-Disposition: form-data; name="resource"

{"version":null,"permissionMask":null,"creationDate":null,"updateDate":null,"label":"Base_domain","description":null,"uri":null,"dataSource":{"dataSourceReference":{"uri":"/public/Samples/Data_Sources/MysqlDataSource"}},"securityFile":null,"schema":{"schemaFile":{"version":null,"permissionMask":null,"creationDate":null,"updateDate":null,"label":"baseDomain_schema","description":"baseDomain_schema","uri":null,"type":"xml","content":null}}}
--Boundary_1_986317581_1496917329819--

2017-06-08 15:52:09,913 com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage log - 2 * Client response received on thread main
2 < 400
2 < Connection: close
2 < Content-Type: application/errorDescriptor+json
2 < Date: Thu, 08 Jun 2017 10:22:45 GMT
2 < P3P: CP="ALL"
2 < Server: Apache-Coyote/1.1
2 < Set-Cookie: userLocale=en_US;Expires=Fri, 9-Jun-2017 10:22:45 GMT;Path=/jasperserver-pro/;HttpOnly,JSESSIONID=06486A07AE4CA182E8BC36E27F1B3F11; Path=/jasperserver-pro/; HttpOnly
2 < Transfer-Encoding: chunked
{"message":"The value \"/baseDomain_schema\" for parameter \"schema\" is invalid.","errorCode":"illegal.parameter.value.error","parameters":["schema","/baseDomain_schema"]}

**Comment by yaroslav-kovalchyk** [comment]
You have to use old style domain schema XML to create semantic layer data source resource. You can find more information about it's structure [here](http://community.jaspersoft.com/documentation/jasperreports-server-user-guide/domain-design-file).
