### ISSUE TITLE
Is there any access denied mechanism in server or this api ?

### ISSUE THREAD

**Issue by peteryuanpan** [Jaspersoft/jrs-rest-java-client#316]
Hi:

  I am building a software. In the software, I have so many times used your api to get file from jasperserver, such as domain, user information, etc.
  However, I found a problem. Sometimes, when I got file so many times, an error occurred. The error seemed "access denied" by server. That's mean: The server didn't allow me to get file. After that, I restarted the software, the problem remained. I still could not get file from server. And then, I restarted the server by tomcat, the problem disappeared. Therefore, I can sure that the problem was caused not by my code but by server.
  So I wanna ask, is there any similar access denied mechanism in server or api that may cause this problem ? Or, if I send requests to server so many many times, will it deny me ? Or, if I send some dangerous request to server, will api deny me ?
  Thanks for your api and sorry for my English.
  Hope for your reply.

**Comment by yaroslav-kovalchyk** [comment]
Looks like a server side bug. Do you have rights to access our support team and log a bug there?

**Comment by peteryuanpan** [comment]
Sorry, I don't have that rights.

**Comment by peteryuanpan** [comment]
Sorry, the problem may caused by JAVA FX but not api and server.
You can close this issue, if you want,
Thanks for your reply.

**Comment by yaroslav-kovalchyk** [comment]
I'm glad to know you resolved your issue!
