### ISSUE TITLE
Is there any way which can push requests one time ?

### ISSUE THREAD

**Issue by peteryuanpan** [Jaspersoft/jrs-rest-java-client#317]
Hello:

  I've found an interesting thing. The most time costs on the process of sending requests and getting requests when using api. That's means, If I have 1000 requests, one way is sending 1000 requests one time and getting one time, another way is sending requests 1000 times and getting 1000 times, the first way is so much faster than the second way.
  I am using your wonderful api to get permission of each folder and file from jasperserver. However, due to so many folders and files, it costs so much time that I can not bear it. Would you like to tell me, is that any way which can push permission even other requests just one time and get just one time ?
  PS : I knew that in user and role model. I can do that. And in report model, I can also get so many folders information in one time. But in permission model, I've not found that way.

Thanks for your reply.

**Comment by yaroslav-kovalchyk** [comment]
Hello,
sorry, but I didn't get your question... Could you please clarify what does it mean: 
"push permission even other requests just one time and get just one time"?
Any sample?

**Comment by peteryuanpan** [comment]
Hello,
Sorry for my English...
For example, I would like to get permission of 100 folders from server.
Now, I have two ways to do that.
First way, send a requests using api to get a folder, and get the permission information of that folder. Ant then, I send the second request. ......, Repeat this way 100 times, I get the permission information of 100 folders.
Second way, make the 100 requests into a List<requests> LIST. Ant then, send this LIST to server, and get a List<reply> LIST2. From LIST2, I can know the permission information of 100 folders.

I've completed the first way. However, I found (in other model) the second way is so much much faster than the first way, especially when the number of folders is very large.

Therefore, is there any way in api similar to the second way now ?

Thanks.

**Comment by peteryuanpan** [comment]
Hello,
Sorry for my English.
For example.
I would like to get permission information of N folders from server.
Now, I have two ways to do that.
First way, I send a request for one folder to server, and then get a reply from server, and I can the permission information of the folder. After that, I send the second request and get the permission information of the second folder. ...... I repeat the way N times. And I get all information of N folders.
Second way, I push the N requests to a ListA and send this list to server and get a reply ListB. From ListB, I can know all information of N folders.

I would like to know, In api, now, is there any way similar to the second way ? Because I know the second way is so much faster than the first way and I need it.

Thanks

**Comment by yaroslav-kovalchyk** [comment]
Thanks for explanation. Now I understand what do you mean. Unfortunately JasperReports Server doesn't provide such REST API. The best you can get for multiple resources are permission masks. Repository REST service provides a way to search resources and each resource in answer will contain permissionMask, that can give you an information about access rights for particular resource for current user. Nothing more.
