### ISSUE TITLE
Dependency crash?

### ISSUE THREAD

**Issue by torbjornsk** [Jaspersoft/jrs-rest-java-client#34]
I am trying to test using this framework, using jetty to start a web-app, and after I've added the dependency, I get this error:

java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;

After some digging it turns out that this is due to a mismatch between the jersey api and the implementation. The dependencies of the project has a dependency to jersey api 2.x (org.glassfish.jersey.core:jersey-client:jar:2.5 -> javax.ws.rs:javax.ws.rs-api:jar:2.0), and also a dependency to jax-rs 1.0 implementation com.sun.jersey:jersey-json:jar:1.18. Will this ever work?

**Comment by yaroslav-kovalchyk** [comment]
Jersey 1.x and 2.x are not compatible. Please upgrade your environment to jersey 2.x if possible.
