### ISSUE TITLE
TEXT Export for jrs-rest-java-client is not available

### ISSUE THREAD

**Issue by GollaManoj** [Jaspersoft/jrs-rest-java-client#355]
we have a requirement of exporting the jasper report in to text format. In this API we doesn't found any class to export the jasper report to text format. On exploring API we found an enum "ReportOutputFormat" contains other formats except TEXT...is there any other possible way to export the report in to Text format?..any help would be appreciated....Thank you.

**Comment by tmatveyeva** [comment]
Hello,

No, there is no possibility to run report in TXT format, but as far as I can see in docs, it is possible to schedule report in TXT, you may try that. I am closing this ticket as it  is not related to JAVA REST client

Regards,
Tetyana
