### ISSUE TITLE
Support for jersey 2.27

### ISSUE THREAD

**Issue by sonersivri** [Jaspersoft/jrs-rest-java-client#358]
2.22.1 version is old for spring boot 2.1 downgrade has risks

**Comment by tggm** [comment]
Also request this. At this point the client is not compatible with Spring-boot 2.1.

**Comment by stuartraetaylor** [comment]
Not sure whether this project is still active, but I have it running with Jersey 2.27 here - https://github.com/stuartraetaylor/jrs-rest-java-client
