### ISSUE TITLE
still using log4j 1.2.17

### ISSUE THREAD

**Issue by dukerobillard** [Jaspersoft/jrs-rest-java-client#373]
looks like jrs-rest-java-client is still using log4j 1.2.17 (under slf4j, I think).  The log4j gang made that "End-of-Life" in August 2015...and with the excitement about the log4shell bug in log4j v2 in December, there's a lot of push to stop using old log4j versions.

Any plans to upgrade to log4j 2.17.1 (or some other slf4j compatible logger)?

**Comment by tmatveyeva** [comment]
Yes, we will publish lib updates with next release.
