### ISSUE TITLE
Switch from Organization class to ClientTenant

### ISSUE THREAD

**Issue by jsrk** [Jaspersoft/jrs-rest-java-client#57]
JRS provides com.jaspersoft.jasperserver.dto.authority.ClientTenant class while the REST client still uses its own com.jaspersoft.jasperserver.jaxrs.client.dto.authority.Organization, which, basically, contains the same set of fields and is used for the same purpose. Switching to ClientTenant from jasperserver-dto.jar is preferred as it is consistent with other API. OrganizationsListWrapper, which uses ClientTenant instead of Organization, is provided by jasperserver-dto.jar as well.

Also it would benefit to update organization adapters code to be consistent with other adapters (i.e. provide updateOrCreate methods).

**Comment by tmatveyeva** [comment]
This was fixed only for SingleOrganizationAdapter, not BatchOrganizationsAdapter

**Comment by yaroslav-kovalchyk** [comment]
Fixed
