### ISSUE TITLE
There's no way to connect anonymously

### ISSUE THREAD

**Issue by Actine** [Jaspersoft/jrs-rest-java-client#63]
Hi,

Sometimes it is not required to authenticate with username/password to perform certain RESTv2 calls, e.g. to get server info, request l10n bundles, or view reports/resources that are accessible for ROLE_ANONYMOUS. However, the client does not let me to perform a request without authenticating with proper credentials (trying to use empty strings in username/password result in 400 Bad Request, and using bogus credentials yield Unauthorized).

Please add possibility to omit authentication, e.g. by adding a separate method in `JasperserverRestClient` (`authenticate()` w/o parameters, or `authenticateAnonymously()`, or `getAnonymousSession()` or such) or allowing to pass null/null in existing `authenticate()` method.

**Comment by yaroslav-kovalchyk** [comment]
Fixed https://github.com/Jaspersoft/jrs-rest-java-client/commit/4d780e9513c05a3e3ec4b9cf2beb81e90d0bd4aa
