### ISSUE TITLE
The whole client is not stateless

### ISSUE THREAD

**Issue by Actine** [Jaspersoft/jrs-rest-java-client#64]
Hi,

There is a pretty critical problem with the client — it is not stateless. From what I discovered, upon calling `authenticate()` it sends a request to `/rest/login` and subsequently uses the cookie for the lifespan of Session object. While this is the only solution for Report Executions service to work (which is not stateless itself), for other services using basic authentication (Authorization header) would be preferred because 1) it is stateless, 2) it requires only one request, and 3) most importantly, it is not affected by session expiration timeouts.

The ideal solution would be using the cookie for Report Executions service only, and basic auth for everything else.

**Comment by yaroslav-kovalchyk** [comment]
BASIC authentication is supported now
