### ISSUE TITLE
The example code line to set inputcontrol parameters doesnt work

### ISSUE THREAD

**Issue by satishcode** [Jaspersoft/jrs-rest-java-client#68]
InputControlStateListWrapper inputControlsValues =
        client.authenticate("jasperadmin", "jasperadmin")
                .reportingService()
                .report("/reports/samples/Cascading_multi_select_report")
                .reportParameters()
                .values()
                .parameter("Cascading_name_single_select", "A & U Stalker Telecommunications, Inc")
                .update()
                .getEntity();

eclipse shows .parameter(".. function doesnt exist.

**Comment by guilherme1603** [comment]
You managed to solve?

**Comment by satishcode** [comment]
no not resolved. but i think something to do with code injection or dependency injection, which i'm not aware where to bring from.

**Comment by yaroslav-kovalchyk** [comment]
New API for input controls is available now. See this:
https://github.com/Jaspersoft/jrs-rest-java-client#input-controls-service
