### ISSUE TITLE
ReportExecutionDescriptor is null even getSerializedContent is there

### ISSUE THREAD

**Issue by skjainlko** [Jaspersoft/jrs-rest-java-client#76]
RestClientConfiguration restClientConfiguration = new RestClientConfiguration(
					"http://localhost:8081/jasperserver");
			restClientConfiguration.setJrsVersion(JRSVersion.v6_0_1);
			
			JasperserverRestClient jasperserverRestClient = new JasperserverRestClient(
					restClientConfiguration);

			Session session = jasperserverRestClient.authenticate(
					"jasperadmin", "jasperadmin");

			
			ReportExecutionRequest reportExecutionRequest = new ReportExecutionRequest();
			reportExecutionRequest.setAsync(Boolean.TRUE);
			reportExecutionRequest.setOutputFormat("html");
			reportExecutionRequest
			.setReportUnitUri("/reports/samples/Cascading_multi_select_report");
			
			
			ReportingService retReportingService = session.reportingService();

			OperationResult<ReportExecutionDescriptor> operationResult = retReportingService
					.newReportExecutionRequest(reportExecutionRequest);

			System.out.println(operationResult.getSerializedContent());
			String id = operationResult.getEntity().getRequestId();
			
			session.logout();

ReportExecutionDescriptor entity comes null, Can you please help

**Comment by TanyaEf** [comment]
The bug can not be reproduced on the latest version of client (6.1.4). Please, try this version and reopen the issue.

**Comment by yaroslav-kovalchyk** [comment]
Please try the latest release version and fill free to reopen if it still doesn't work
