### ISSUE TITLE
With Jasperserver 6.0.1 PRO the /rest/login call raises NPE

### ISSUE THREAD

**Issue by nicolaslledosnef** [Jaspersoft/jrs-rest-java-client#78]
When calling client.authenticate the login method raises an NPE.
This is causes by the fact that no cookie is received.
The reason of the cookie absence is that on 6.0.1 Pro there are 2 redirect for a single rest call.

Here is the access log:
```log
"POST /jasperserver-pro2/rest/login HTTP/1.1" 302 -
"GET /jasperserver-pro2/loginsuccess.html;jsessionid=C09B3FA8562359EC75AC0A4DB84CC590 HTTP/1.1" 302 -
"GET /jasperserver-pro2/flow.html;jsessionid=C09B3FA8562359EC75AC0A4DB84CC590?_flowId=homeFlow HTTP/1.1" 200 
```

The response with status code 302 contains the cookie in the header.
Unfortunately the jrs-client seems to follow the redirects to the last response which doesn't have the cookie in headers (but in the url).

I'll try to fork the source to add 
```java 
client.property(ClientProperties.FOLLOW_REDIRECTS, Boolean.FALSE)
```
Here is the stack
```exception
Exception in thread "main" java.lang.NullPointerException
	at com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.login(SessionStorage.java:105)
	at com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.init(SessionStorage.java:93)
	at com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.<init>(SessionStorage.java:50)
	at com.jaspersoft.jasperserver.jaxrs.client.core.JasperserverRestClient.authenticate(JasperserverRestClient.java:35)
	at com.snef.si.edition.engine.EditionProcessor.doBatchGenerations(EditionProcessor.java:359)
	at com.snef.si.edition.engine.EditionProcessor.doGenerations(EditionProcessor.java:326)
	at com.snef.si.edition.engine.EditionProcessor.process(EditionProcessor.java:205)
	at com.snef.si.edition.engine.EditionProcessor.main(EditionProcessor.java:123)
```

**Comment by Krasnyanskiy** [comment]
It's quite strange because I tried to reproduce this issue on JRS `6.0.1 Pro` and for me it works just fine.

**Comment by nicolaslledosnef** [comment]
Do you have any redirect at all ? FYI, I upgraded from a 5.6.1 Pro (not using the overlay).

**Comment by Krasnyanskiy** [comment]
Here are logs of requests:
#### Request
```
POST /jasperserver-pro/rest/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: Jersey/2.5 (HttpUrlConnection 1.7.0_60)
Host: localhost:8080
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 41

j_username=superuser&j_password=superuser
```
#### Responce
```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
P3P: CP="ALL"
Set-Cookie: JSESSIONID=AE40143A0D5467D57EBFA3B0C92E17B6; Path=/jasperserver-pro/; HttpOnly
Content-Type: text/xml;charset=UTF-8
Content-Length: 0
Date: Fri, 15 May 2015 17:34:10 GMT
```
#### Request
```
GET /jasperserver-pro/rest_v2/resources?folderUri=/&recursive=true HTTP/1.1
Accept: application/json
Cookie: JSESSIONID=AE40143A0D5467D57EBFA3B0C92E17B6
User-Agent: Jersey/2.5 (HttpUrlConnection 1.7.0_60)
Host: localhost:4444
Connection: keep-alive
```
#### Responce
```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: private
Expires: Thu, 01 Jan 1970 03:00:00 EET
P3P: CP="ALL"
Set-Cookie: userLocale=en_US;Expires=Sat, 16-May-2015 17:34:11 GMT;HttpOnly
Start-Index: 0
Result-Count: 100
Total-Count: 776
Content-Type: application/json
Transfer-Encoding: chunked
Date: Fri, 15 May 2015 17:34:13 GMT

2000
{
  // content ommited
}
0
```
Don't be scared of `localhost:4444` :smiley: I'm using request interceptor from my IDE. As you can see there is no redirection.

**Comment by Krasnyanskiy** [comment]
I didn't check it but you could try to use a simple boolean literal instead of `Boolean` wrapper.
```java
client.property(ClientProperties.FOLLOW_REDIRECTS, false)
```

**Comment by soylentgreen81** [comment]
I had the same issue with CE server 6.0.1 

It's strange because it worked for several weeks and then suddenly started throwing exactly the same NPE.

I patched the code (added a new field followRedirects to RestConfiguration and changed the behaviour in SessionStorage). Now it is working again.

**Comment by RockyRx** [comment]
I'm having the same issue. Does ```client.property(ClientProperties.FOLLOW_REDIRECTS, Boolean.FALSE)``` added to the latest build?

**Comment by Krasnyanskiy** [comment]
No, it does not added.

**Comment by RockyRx** [comment]
Is there a workaround for now? I'm having a little trouble after upgrading to 6.1.0

**Comment by khcitizen** [comment]
Hi everyone,

Those of you affected by the issue with NPE please check if you are using external authentication. If you do try disabling it by removing corresponding applicationContext-externalAuth*.xml file from WEB-INF folder.

**Comment by nicolaslledosnef** [comment]
Maybe external authentication has something to do with the NPE. But disabling it, is not a workaround I would try.

I eventually edited `com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.init()`.
I have added the property and set it to false.

But I have to change the if control statement of `com.jaspersoft.jasperserver.jaxrs.client.core.SessionStorage.login()`

````java
if (response.getStatus() == ResponseStatus.OK ) {
````
became
````java
if (response.getStatus() == ResponseStatus.OK || 
response.getStatus() == ResponseStatus.FOUND ) {
````

````java
package com.jaspersoft.jasperserver.jaxrs.client.core;

public final class ResponseStatus {
 (...)
    public static final int FOUND = 302;
 (...)
}
````

now it works.

**Comment by elfo-eap** [comment]
Hi nicolaslledosnef, I have the same problem. How did you edit the files you mention?
Regards.

**Comment by yaroslav-kovalchyk** [comment]
Now default authentication mechanism is j_spring_security_check. Shouldn't have any issues.

**Comment by yaroslav-kovalchyk** [comment]
please comment here if any problem and I'll reopen the issue

**Comment by RockyRx** [comment]
Does the new version added to the Maven repo?

**Comment by yaroslav-kovalchyk** [comment]
Yes it's here: http://jaspersoft.artifactoryonline.com/jaspersoft/webapp/#/artifacts/browse/tree/General/repo/com/jaspersoft/jrs-rest-java-client/6.0.8
