### ISSUE TITLE
Add BASIC authentication and SSL cert support

### ISSUE THREAD

**Issue by a-simkin** [Jaspersoft/jrs-rest-java-client#84]
Customer's case #60983:

In the end I couldn't get the [client](https://github.com/Jaspersoft/jrs-rest-java-client) to authenticate. Looking at the code, it only supports form-based authentication and there's no support for BASIC auth. And there was an issue with the ssl certs. So I stopped using it and swapped over to the Jersey's REST client.

**Comment by Krasnyanskiy** [comment]
> Customer's case #60983

Could you describe that case. And provide my with some code.

**Comment by a-simkin** [comment]
that's the only comment I got from customer...Could you confirm that the current release of the client supports BASIC auth ?

**Comment by Krasnyanskiy** [comment]
Currently it doesn't support that kind of auth.

**Comment by yaroslav-kovalchyk** [comment]
Now BASIC authentication is supported
