### ISSUE TITLE
Add docs for Settings Service

### ISSUE THREAD

**Issue by Krasnyanskiy** [Jaspersoft/jrs-rest-java-client#87]
Regarding the request #86, we need to add some nice documentation to Settings Service as a part of [Administration services](https://github.com/Jaspersoft/jrs-rest-java-client#administration-services) in Readme file.

**Comment by yaroslav-kovalchyk** [comment]
Fixed https://github.com/Jaspersoft/jrs-rest-java-client/commit/4d780e9513c05a3e3ec4b9cf2beb81e90d0bd4aa
