### ISSUE TITLE
Add DTO support to Settings Service

### ISSUE THREAD

**Issue by Krasnyanskiy** [Jaspersoft/jrs-rest-java-client#89]
We have a code
```java
Map settings = session
    .settingsService()
        .settings()
            .group(REQUEST)
                .getEntity();
```
As you can see it returns a map. It is certainly good to have such flexible container, but what if we want to use something different, let's say some clear and descriptive DTO? In that case, we should add a mechanism to specify DTO type implicitly and return not a map but DTO instance, like in the code below
```java
RequestServerSettings requestServerSettings = session
        .settingsService()
            .settings()
                .group(ServerSettingsGroup.REQUEST)
                    .getEntity();
```
or
```java
InputControlServerSettings icServerSettings = session
        .settingsService()
            .settings()
                .group(ServerSettingsGroup.INPUT_CONTROL)
                    .getEntity();
```

**Comment by yaroslav-kovalchyk** [comment]
Fixed here: https://github.com/Jaspersoft/jrs-rest-java-client/commit/4729c9354385568d6264b54681a9086837974c23
