### ISSUE TITLE
Return of Deleting Resources

### ISSUE THREAD

**Issue by guilherme1603** [Jaspersoft/jrs-rest-java-client#93]
Hello, I have a issue with the return of the OperationResult. The return value of 'result' is null, but the operation is accomplished with success. When the folder or file not exist, the result also is null.

   ```java
   OperationResult result = client
        .authenticate("jasperadmin", "jasperadmin")
        .resourcesService()
        .resource("/reports/testFolder")
        .delete();
   ```

Thanks.

**Comment by Krasnyanskiy** [comment]
Guilherme,
You could download a new version (with fixed bug) from [Artifactory](http://jaspersoft.artifactoryonline.com/jaspersoft/webapp/browserepo.html?3&pathId=jaspersoft-clients-releases:com/jaspersoft/jrs-rest-java-client). Or use Maven to grab dependencies:
```xml
<dependency>
   <groupId>com.jaspersoft</groupId>
   <artifactId>jrs-rest-java-client</artifactId>
   <version>6.0.4</version>
</dependency>
```

**Comment by guilherme1603** [comment]
Hello, thanks for quick response, but I think that the bug not was fixed, because yet the response is null.
My code:
```java
        OperationResult result = session
	            .resourcesService()
	            .resource("/images/Teste2.png")
	            .delete();
	    
	    System.out.println(result.getEntity());
	    System.out.println(result.getResponse().getStatusInfo());
```
Response:
null
No Content

Thanks

**Comment by Krasnyanskiy** [comment]
Do you use the [latest](http://jaspersoft.artifactoryonline.com/jaspersoft/webapp/browserepo.html?0&pathId=jaspersoft-clients-releases:com/jaspersoft/jrs-rest-java-client) version of the client?

**Comment by guilherme1603** [comment]
Yes, i am using the 6.0.4 with dependencies. 

Now, I used your code, there is a response, but it always is the same. For example, if the folder exist and I delete it, the response is 204, and if the folder does not exist and I delete, the response also is 204. 

So I can not know whether deleted or not deleted.

**Comment by Krasnyanskiy** [comment]
It is expected REST behaviour.

**Comment by guilherme1603** [comment]
Ok so, thank you very much.

**Comment by Krasnyanskiy** [comment]
However, we can add some method to check is resourse is available:

```java
boolean isResourceAvailable = session
        .resourcesService()
        .resource("/reports/SomeReport")
        .isAvailable();
```
