### ISSUE TITLE
Cannot run report with multi value parameter

### ISSUE THREAD

**Issue by tmatveyeva** [Jaspersoft/jrs-rest-java-client#94]
When running report via reportingService, it's possible to specify parameter for report. And RunReportAdapter.parameter method accept to String parameters. While it should be possible to add several values to one parameter (Multi Select IC on UI).

**Comment by Krasnyanskiy** [comment]
Is this feature supported by our Web Services?

**Comment by tmatveyeva** [comment]
When running report Client Report Options are used and Client Report Options support list (array) as option value http://community.jaspersoft.com/documentation/tibco-jasperreports-server-web-services-guide/v610/creating-report-options-0

**Comment by Krasnyanskiy** [comment]
Ok, thanks.

**Comment by yaroslav-kovalchyk** [comment]
Fixed https://github.com/Jaspersoft/jrs-rest-java-client/commit/4d780e9513c05a3e3ec4b9cf2beb81e90d0bd4aa
